template: testify
template-data:
  unroll-variadic: true
filename: "mock_{{.InterfaceName}}.go"
packages:
  go.lumeweb.com/portal-plugin-quota/core:
    interfaces:
      GrantManager: {}
      PolicyEnforcer: {}
      QuotaService: {}
      UsageManager: {}
      UsageAggregator: {}
      QuotaPlanManager: {}
      LimitResolver: {}
      ConfigManager: {}