// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-quota/internal/db/models"
)

// NewMockLimitResolver creates a new instance of MockLimitResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimitResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimitResolver {
	mock := &MockLimitResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLimitResolver is an autogenerated mock type for the LimitResolver type
type MockLimitResolver struct {
	mock.Mock
}

type MockLimitResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimitResolver) EXPECT() *MockLimitResolver_Expecter {
	return &MockLimitResolver_Expecter{mock: &_m.Mock}
}

// ApplyLimit provides a mock function for the type MockLimitResolver
func (_mock *MockLimitResolver) ApplyLimit(ctx context.Context, dest **uint64, source int64, limitName string, options ...LimitOption) error {
	// LimitOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, source, limitName)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ApplyLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, **uint64, int64, string, ...LimitOption) error); ok {
		r0 = returnFunc(ctx, dest, source, limitName, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLimitResolver_ApplyLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyLimit'
type MockLimitResolver_ApplyLimit_Call struct {
	*mock.Call
}

// ApplyLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - dest **uint64
//   - source int64
//   - limitName string
//   - options ...LimitOption
func (_e *MockLimitResolver_Expecter) ApplyLimit(ctx interface{}, dest interface{}, source interface{}, limitName interface{}, options ...interface{}) *MockLimitResolver_ApplyLimit_Call {
	return &MockLimitResolver_ApplyLimit_Call{Call: _e.mock.On("ApplyLimit",
		append([]interface{}{ctx, dest, source, limitName}, options...)...)}
}

func (_c *MockLimitResolver_ApplyLimit_Call) Run(run func(ctx context.Context, dest **uint64, source int64, limitName string, options ...LimitOption)) *MockLimitResolver_ApplyLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 **uint64
		if args[1] != nil {
			arg1 = args[1].(**uint64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []LimitOption
		variadicArgs := make([]LimitOption, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(LimitOption)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockLimitResolver_ApplyLimit_Call) Return(err error) *MockLimitResolver_ApplyLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLimitResolver_ApplyLimit_Call) RunAndReturn(run func(ctx context.Context, dest **uint64, source int64, limitName string, options ...LimitOption) error) *MockLimitResolver_ApplyLimit_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveEffectiveLimits provides a mock function for the type MockLimitResolver
func (_mock *MockLimitResolver) ResolveEffectiveLimits(ctx context.Context, config *models.UserQuotaConfig, policy models.EnforcementPolicy) (*EffectiveLimits, error) {
	ret := _mock.Called(ctx, config, policy)

	if len(ret) == 0 {
		panic("no return value specified for ResolveEffectiveLimits")
	}

	var r0 *EffectiveLimits
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserQuotaConfig, models.EnforcementPolicy) (*EffectiveLimits, error)); ok {
		return returnFunc(ctx, config, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserQuotaConfig, models.EnforcementPolicy) *EffectiveLimits); ok {
		r0 = returnFunc(ctx, config, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EffectiveLimits)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UserQuotaConfig, models.EnforcementPolicy) error); ok {
		r1 = returnFunc(ctx, config, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLimitResolver_ResolveEffectiveLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveEffectiveLimits'
type MockLimitResolver_ResolveEffectiveLimits_Call struct {
	*mock.Call
}

// ResolveEffectiveLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - config *models.UserQuotaConfig
//   - policy models.EnforcementPolicy
func (_e *MockLimitResolver_Expecter) ResolveEffectiveLimits(ctx interface{}, config interface{}, policy interface{}) *MockLimitResolver_ResolveEffectiveLimits_Call {
	return &MockLimitResolver_ResolveEffectiveLimits_Call{Call: _e.mock.On("ResolveEffectiveLimits", ctx, config, policy)}
}

func (_c *MockLimitResolver_ResolveEffectiveLimits_Call) Run(run func(ctx context.Context, config *models.UserQuotaConfig, policy models.EnforcementPolicy)) *MockLimitResolver_ResolveEffectiveLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UserQuotaConfig
		if args[1] != nil {
			arg1 = args[1].(*models.UserQuotaConfig)
		}
		var arg2 models.EnforcementPolicy
		if args[2] != nil {
			arg2 = args[2].(models.EnforcementPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLimitResolver_ResolveEffectiveLimits_Call) Return(effectiveLimits *EffectiveLimits, err error) *MockLimitResolver_ResolveEffectiveLimits_Call {
	_c.Call.Return(effectiveLimits, err)
	return _c
}

func (_c *MockLimitResolver_ResolveEffectiveLimits_Call) RunAndReturn(run func(ctx context.Context, config *models.UserQuotaConfig, policy models.EnforcementPolicy) (*EffectiveLimits, error)) *MockLimitResolver_ResolveEffectiveLimits_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateThresholdValue provides a mock function for the type MockLimitResolver
func (_mock *MockLimitResolver) ValidateThresholdValue(ctx context.Context, thresholdValue int64, thresholdType string) error {
	ret := _mock.Called(ctx, thresholdValue, thresholdType)

	if len(ret) == 0 {
		panic("no return value specified for ValidateThresholdValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, thresholdValue, thresholdType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLimitResolver_ValidateThresholdValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateThresholdValue'
type MockLimitResolver_ValidateThresholdValue_Call struct {
	*mock.Call
}

// ValidateThresholdValue is a helper method to define mock.On call
//   - ctx context.Context
//   - thresholdValue int64
//   - thresholdType string
func (_e *MockLimitResolver_Expecter) ValidateThresholdValue(ctx interface{}, thresholdValue interface{}, thresholdType interface{}) *MockLimitResolver_ValidateThresholdValue_Call {
	return &MockLimitResolver_ValidateThresholdValue_Call{Call: _e.mock.On("ValidateThresholdValue", ctx, thresholdValue, thresholdType)}
}

func (_c *MockLimitResolver_ValidateThresholdValue_Call) Run(run func(ctx context.Context, thresholdValue int64, thresholdType string)) *MockLimitResolver_ValidateThresholdValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLimitResolver_ValidateThresholdValue_Call) Return(err error) *MockLimitResolver_ValidateThresholdValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLimitResolver_ValidateThresholdValue_Call) RunAndReturn(run func(ctx context.Context, thresholdValue int64, thresholdType string) error) *MockLimitResolver_ValidateThresholdValue_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateThresholdVsLimit provides a mock function for the type MockLimitResolver
func (_mock *MockLimitResolver) ValidateThresholdVsLimit(ctx context.Context, thresholdValue int64, limitValue int64, thresholdType string) error {
	ret := _mock.Called(ctx, thresholdValue, limitValue, thresholdType)

	if len(ret) == 0 {
		panic("no return value specified for ValidateThresholdVsLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = returnFunc(ctx, thresholdValue, limitValue, thresholdType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLimitResolver_ValidateThresholdVsLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateThresholdVsLimit'
type MockLimitResolver_ValidateThresholdVsLimit_Call struct {
	*mock.Call
}

// ValidateThresholdVsLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - thresholdValue int64
//   - limitValue int64
//   - thresholdType string
func (_e *MockLimitResolver_Expecter) ValidateThresholdVsLimit(ctx interface{}, thresholdValue interface{}, limitValue interface{}, thresholdType interface{}) *MockLimitResolver_ValidateThresholdVsLimit_Call {
	return &MockLimitResolver_ValidateThresholdVsLimit_Call{Call: _e.mock.On("ValidateThresholdVsLimit", ctx, thresholdValue, limitValue, thresholdType)}
}

func (_c *MockLimitResolver_ValidateThresholdVsLimit_Call) Run(run func(ctx context.Context, thresholdValue int64, limitValue int64, thresholdType string)) *MockLimitResolver_ValidateThresholdVsLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLimitResolver_ValidateThresholdVsLimit_Call) Return(err error) *MockLimitResolver_ValidateThresholdVsLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLimitResolver_ValidateThresholdVsLimit_Call) RunAndReturn(run func(ctx context.Context, thresholdValue int64, limitValue int64, thresholdType string) error) *MockLimitResolver_ValidateThresholdVsLimit_Call {
	_c.Call.Return(run)
	return _c
}
