// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-quota/internal/db/models"
)

// NewMockQuotaPlanManager creates a new instance of MockQuotaPlanManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaPlanManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaPlanManager {
	mock := &MockQuotaPlanManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuotaPlanManager is an autogenerated mock type for the QuotaPlanManager type
type MockQuotaPlanManager struct {
	mock.Mock
}

type MockQuotaPlanManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaPlanManager) EXPECT() *MockQuotaPlanManager_Expecter {
	return &MockQuotaPlanManager_Expecter{mock: &_m.Mock}
}

// GetDefaultQuotaPlan provides a mock function for the type MockQuotaPlanManager
func (_mock *MockQuotaPlanManager) GetDefaultQuotaPlan(ctx context.Context) (*models.QuotaPlan, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultQuotaPlan")
	}

	var r0 *models.QuotaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.QuotaPlan, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.QuotaPlan); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaPlanManager_GetDefaultQuotaPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultQuotaPlan'
type MockQuotaPlanManager_GetDefaultQuotaPlan_Call struct {
	*mock.Call
}

// GetDefaultQuotaPlan is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuotaPlanManager_Expecter) GetDefaultQuotaPlan(ctx interface{}) *MockQuotaPlanManager_GetDefaultQuotaPlan_Call {
	return &MockQuotaPlanManager_GetDefaultQuotaPlan_Call{Call: _e.mock.On("GetDefaultQuotaPlan", ctx)}
}

func (_c *MockQuotaPlanManager_GetDefaultQuotaPlan_Call) Run(run func(ctx context.Context)) *MockQuotaPlanManager_GetDefaultQuotaPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaPlanManager_GetDefaultQuotaPlan_Call) Return(quotaPlan *models.QuotaPlan, err error) *MockQuotaPlanManager_GetDefaultQuotaPlan_Call {
	_c.Call.Return(quotaPlan, err)
	return _c
}

func (_c *MockQuotaPlanManager_GetDefaultQuotaPlan_Call) RunAndReturn(run func(ctx context.Context) (*models.QuotaPlan, error)) *MockQuotaPlanManager_GetDefaultQuotaPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaPlanByID provides a mock function for the type MockQuotaPlanManager
func (_mock *MockQuotaPlanManager) GetQuotaPlanByID(ctx context.Context, id uint64) (*models.QuotaPlan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaPlanByID")
	}

	var r0 *models.QuotaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*models.QuotaPlan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *models.QuotaPlan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaPlanManager_GetQuotaPlanByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaPlanByID'
type MockQuotaPlanManager_GetQuotaPlanByID_Call struct {
	*mock.Call
}

// GetQuotaPlanByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockQuotaPlanManager_Expecter) GetQuotaPlanByID(ctx interface{}, id interface{}) *MockQuotaPlanManager_GetQuotaPlanByID_Call {
	return &MockQuotaPlanManager_GetQuotaPlanByID_Call{Call: _e.mock.On("GetQuotaPlanByID", ctx, id)}
}

func (_c *MockQuotaPlanManager_GetQuotaPlanByID_Call) Run(run func(ctx context.Context, id uint64)) *MockQuotaPlanManager_GetQuotaPlanByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaPlanManager_GetQuotaPlanByID_Call) Return(quotaPlan *models.QuotaPlan, err error) *MockQuotaPlanManager_GetQuotaPlanByID_Call {
	_c.Call.Return(quotaPlan, err)
	return _c
}

func (_c *MockQuotaPlanManager_GetQuotaPlanByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*models.QuotaPlan, error)) *MockQuotaPlanManager_GetQuotaPlanByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaPlanByName provides a mock function for the type MockQuotaPlanManager
func (_mock *MockQuotaPlanManager) GetQuotaPlanByName(ctx context.Context, name string) (*models.QuotaPlan, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaPlanByName")
	}

	var r0 *models.QuotaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.QuotaPlan, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.QuotaPlan); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuotaPlanManager_GetQuotaPlanByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaPlanByName'
type MockQuotaPlanManager_GetQuotaPlanByName_Call struct {
	*mock.Call
}

// GetQuotaPlanByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQuotaPlanManager_Expecter) GetQuotaPlanByName(ctx interface{}, name interface{}) *MockQuotaPlanManager_GetQuotaPlanByName_Call {
	return &MockQuotaPlanManager_GetQuotaPlanByName_Call{Call: _e.mock.On("GetQuotaPlanByName", ctx, name)}
}

func (_c *MockQuotaPlanManager_GetQuotaPlanByName_Call) Run(run func(ctx context.Context, name string)) *MockQuotaPlanManager_GetQuotaPlanByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaPlanManager_GetQuotaPlanByName_Call) Return(quotaPlan *models.QuotaPlan, err error) *MockQuotaPlanManager_GetQuotaPlanByName_Call {
	_c.Call.Return(quotaPlan, err)
	return _c
}

func (_c *MockQuotaPlanManager_GetQuotaPlanByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*models.QuotaPlan, error)) *MockQuotaPlanManager_GetQuotaPlanByName_Call {
	_c.Call.Return(run)
	return _c
}
