// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/queryutil"
	"gorm.io/gorm"
)

// NewMockGrantManager creates a new instance of MockGrantManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrantManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrantManager {
	mock := &MockGrantManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrantManager is an autogenerated mock type for the GrantManager type
type MockGrantManager struct {
	mock.Mock
}

type MockGrantManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrantManager) EXPECT() *MockGrantManager_Expecter {
	return &MockGrantManager_Expecter{mock: &_m.Mock}
}

// CalculateAvailableBytes provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) CalculateAvailableBytes(grants []*AllowanceGrant) uint64 {
	ret := _mock.Called(grants)

	if len(ret) == 0 {
		panic("no return value specified for CalculateAvailableBytes")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func([]*AllowanceGrant) uint64); ok {
		r0 = returnFunc(grants)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// MockGrantManager_CalculateAvailableBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateAvailableBytes'
type MockGrantManager_CalculateAvailableBytes_Call struct {
	*mock.Call
}

// CalculateAvailableBytes is a helper method to define mock.On call
//   - grants []*AllowanceGrant
func (_e *MockGrantManager_Expecter) CalculateAvailableBytes(grants interface{}) *MockGrantManager_CalculateAvailableBytes_Call {
	return &MockGrantManager_CalculateAvailableBytes_Call{Call: _e.mock.On("CalculateAvailableBytes", grants)}
}

func (_c *MockGrantManager_CalculateAvailableBytes_Call) Run(run func(grants []*AllowanceGrant)) *MockGrantManager_CalculateAvailableBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*AllowanceGrant
		if args[0] != nil {
			arg0 = args[0].([]*AllowanceGrant)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrantManager_CalculateAvailableBytes_Call) Return(v uint64) *MockGrantManager_CalculateAvailableBytes_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockGrantManager_CalculateAvailableBytes_Call) RunAndReturn(run func(grants []*AllowanceGrant) uint64) *MockGrantManager_CalculateAvailableBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeFromGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) ConsumeFromGrants(ctx context.Context, userID uint, grantType GrantType, bytes uint64, usageDetailID uint, tx *gorm.DB) ([]*AllowanceConsumption, error) {
	ret := _mock.Called(ctx, userID, grantType, bytes, usageDetailID, tx)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeFromGrants")
	}

	var r0 []*AllowanceConsumption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, GrantType, uint64, uint, *gorm.DB) ([]*AllowanceConsumption, error)); ok {
		return returnFunc(ctx, userID, grantType, bytes, usageDetailID, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, GrantType, uint64, uint, *gorm.DB) []*AllowanceConsumption); ok {
		r0 = returnFunc(ctx, userID, grantType, bytes, usageDetailID, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceConsumption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, GrantType, uint64, uint, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, userID, grantType, bytes, usageDetailID, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_ConsumeFromGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeFromGrants'
type MockGrantManager_ConsumeFromGrants_Call struct {
	*mock.Call
}

// ConsumeFromGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - grantType GrantType
//   - bytes uint64
//   - usageDetailID uint
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) ConsumeFromGrants(ctx interface{}, userID interface{}, grantType interface{}, bytes interface{}, usageDetailID interface{}, tx interface{}) *MockGrantManager_ConsumeFromGrants_Call {
	return &MockGrantManager_ConsumeFromGrants_Call{Call: _e.mock.On("ConsumeFromGrants", ctx, userID, grantType, bytes, usageDetailID, tx)}
}

func (_c *MockGrantManager_ConsumeFromGrants_Call) Run(run func(ctx context.Context, userID uint, grantType GrantType, bytes uint64, usageDetailID uint, tx *gorm.DB)) *MockGrantManager_ConsumeFromGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 GrantType
		if args[2] != nil {
			arg2 = args[2].(GrantType)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 uint
		if args[4] != nil {
			arg4 = args[4].(uint)
		}
		var arg5 *gorm.DB
		if args[5] != nil {
			arg5 = args[5].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockGrantManager_ConsumeFromGrants_Call) Return(vs []*AllowanceConsumption, err error) *MockGrantManager_ConsumeFromGrants_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_ConsumeFromGrants_Call) RunAndReturn(run func(ctx context.Context, userID uint, grantType GrantType, bytes uint64, usageDetailID uint, tx *gorm.DB) ([]*AllowanceConsumption, error)) *MockGrantManager_ConsumeFromGrants_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAllowanceGrant provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) CreateAllowanceGrant(ctx context.Context, userID uint, grant *AllowanceGrant) error {
	ret := _mock.Called(ctx, userID, grant)

	if len(ret) == 0 {
		panic("no return value specified for CreateAllowanceGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *AllowanceGrant) error); ok {
		r0 = returnFunc(ctx, userID, grant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantManager_CreateAllowanceGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAllowanceGrant'
type MockGrantManager_CreateAllowanceGrant_Call struct {
	*mock.Call
}

// CreateAllowanceGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - grant *AllowanceGrant
func (_e *MockGrantManager_Expecter) CreateAllowanceGrant(ctx interface{}, userID interface{}, grant interface{}) *MockGrantManager_CreateAllowanceGrant_Call {
	return &MockGrantManager_CreateAllowanceGrant_Call{Call: _e.mock.On("CreateAllowanceGrant", ctx, userID, grant)}
}

func (_c *MockGrantManager_CreateAllowanceGrant_Call) Run(run func(ctx context.Context, userID uint, grant *AllowanceGrant)) *MockGrantManager_CreateAllowanceGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *AllowanceGrant
		if args[2] != nil {
			arg2 = args[2].(*AllowanceGrant)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantManager_CreateAllowanceGrant_Call) Return(err error) *MockGrantManager_CreateAllowanceGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantManager_CreateAllowanceGrant_Call) RunAndReturn(run func(ctx context.Context, userID uint, grant *AllowanceGrant) error) *MockGrantManager_CreateAllowanceGrant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAllowanceGrantLocked provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) CreateAllowanceGrantLocked(ctx context.Context, userID uint, grant *AllowanceGrant, tx *gorm.DB) error {
	ret := _mock.Called(ctx, userID, grant, tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateAllowanceGrantLocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *AllowanceGrant, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, userID, grant, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantManager_CreateAllowanceGrantLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAllowanceGrantLocked'
type MockGrantManager_CreateAllowanceGrantLocked_Call struct {
	*mock.Call
}

// CreateAllowanceGrantLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - grant *AllowanceGrant
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) CreateAllowanceGrantLocked(ctx interface{}, userID interface{}, grant interface{}, tx interface{}) *MockGrantManager_CreateAllowanceGrantLocked_Call {
	return &MockGrantManager_CreateAllowanceGrantLocked_Call{Call: _e.mock.On("CreateAllowanceGrantLocked", ctx, userID, grant, tx)}
}

func (_c *MockGrantManager_CreateAllowanceGrantLocked_Call) Run(run func(ctx context.Context, userID uint, grant *AllowanceGrant, tx *gorm.DB)) *MockGrantManager_CreateAllowanceGrantLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *AllowanceGrant
		if args[2] != nil {
			arg2 = args[2].(*AllowanceGrant)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrantManager_CreateAllowanceGrantLocked_Call) Return(err error) *MockGrantManager_CreateAllowanceGrantLocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantManager_CreateAllowanceGrantLocked_Call) RunAndReturn(run func(ctx context.Context, userID uint, grant *AllowanceGrant, tx *gorm.DB) error) *MockGrantManager_CreateAllowanceGrantLocked_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateGrant provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) DeactivateGrant(ctx context.Context, grantID uint) error {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantManager_DeactivateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateGrant'
type MockGrantManager_DeactivateGrant_Call struct {
	*mock.Call
}

// DeactivateGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID uint
func (_e *MockGrantManager_Expecter) DeactivateGrant(ctx interface{}, grantID interface{}) *MockGrantManager_DeactivateGrant_Call {
	return &MockGrantManager_DeactivateGrant_Call{Call: _e.mock.On("DeactivateGrant", ctx, grantID)}
}

func (_c *MockGrantManager_DeactivateGrant_Call) Run(run func(ctx context.Context, grantID uint)) *MockGrantManager_DeactivateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_DeactivateGrant_Call) Return(err error) *MockGrantManager_DeactivateGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantManager_DeactivateGrant_Call) RunAndReturn(run func(ctx context.Context, grantID uint) error) *MockGrantManager_DeactivateGrant_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrants(ctx context.Context, userID uint) ([]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrants")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrants'
type MockGrantManager_GetActiveGrants_Call struct {
	*mock.Call
}

// GetActiveGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockGrantManager_Expecter) GetActiveGrants(ctx interface{}, userID interface{}) *MockGrantManager_GetActiveGrants_Call {
	return &MockGrantManager_GetActiveGrants_Call{Call: _e.mock.On("GetActiveGrants", ctx, userID)}
}

func (_c *MockGrantManager_GetActiveGrants_Call) Run(run func(ctx context.Context, userID uint)) *MockGrantManager_GetActiveGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrants_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrants_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrants_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrants_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsByType provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsByType(ctx context.Context, userID uint, grantType GrantType) ([]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID, grantType)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsByType")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, GrantType) ([]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID, grantType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, GrantType) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID, grantType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, GrantType) error); ok {
		r1 = returnFunc(ctx, userID, grantType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsByType'
type MockGrantManager_GetActiveGrantsByType_Call struct {
	*mock.Call
}

// GetActiveGrantsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - grantType GrantType
func (_e *MockGrantManager_Expecter) GetActiveGrantsByType(ctx interface{}, userID interface{}, grantType interface{}) *MockGrantManager_GetActiveGrantsByType_Call {
	return &MockGrantManager_GetActiveGrantsByType_Call{Call: _e.mock.On("GetActiveGrantsByType", ctx, userID, grantType)}
}

func (_c *MockGrantManager_GetActiveGrantsByType_Call) Run(run func(ctx context.Context, userID uint, grantType GrantType)) *MockGrantManager_GetActiveGrantsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 GrantType
		if args[2] != nil {
			arg2 = args[2].(GrantType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByType_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsByType_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByType_Call) RunAndReturn(run func(ctx context.Context, userID uint, grantType GrantType) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsByTypeBatch provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsByTypeBatch(ctx context.Context, userIDs []uint, grantType GrantType) (map[uint][]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, userIDs, grantType)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsByTypeBatch")
	}

	var r0 map[uint][]*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint, GrantType) (map[uint][]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, userIDs, grantType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint, GrantType) map[uint][]*AllowanceGrant); ok {
		r0 = returnFunc(ctx, userIDs, grantType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint][]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint, GrantType) error); ok {
		r1 = returnFunc(ctx, userIDs, grantType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsByTypeBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsByTypeBatch'
type MockGrantManager_GetActiveGrantsByTypeBatch_Call struct {
	*mock.Call
}

// GetActiveGrantsByTypeBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uint
//   - grantType GrantType
func (_e *MockGrantManager_Expecter) GetActiveGrantsByTypeBatch(ctx interface{}, userIDs interface{}, grantType interface{}) *MockGrantManager_GetActiveGrantsByTypeBatch_Call {
	return &MockGrantManager_GetActiveGrantsByTypeBatch_Call{Call: _e.mock.On("GetActiveGrantsByTypeBatch", ctx, userIDs, grantType)}
}

func (_c *MockGrantManager_GetActiveGrantsByTypeBatch_Call) Run(run func(ctx context.Context, userIDs []uint, grantType GrantType)) *MockGrantManager_GetActiveGrantsByTypeBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint
		if args[1] != nil {
			arg1 = args[1].([]uint)
		}
		var arg2 GrantType
		if args[2] != nil {
			arg2 = args[2].(GrantType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByTypeBatch_Call) Return(uintToVs map[uint][]*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsByTypeBatch_Call {
	_c.Call.Return(uintToVs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByTypeBatch_Call) RunAndReturn(run func(ctx context.Context, userIDs []uint, grantType GrantType) (map[uint][]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsByTypeBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsByTypeLocked provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsByTypeLocked(ctx context.Context, userID uint, grantType GrantType, tx *gorm.DB) ([]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID, grantType, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsByTypeLocked")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, GrantType, *gorm.DB) ([]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID, grantType, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, GrantType, *gorm.DB) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID, grantType, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, GrantType, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, userID, grantType, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsByTypeLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsByTypeLocked'
type MockGrantManager_GetActiveGrantsByTypeLocked_Call struct {
	*mock.Call
}

// GetActiveGrantsByTypeLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - grantType GrantType
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) GetActiveGrantsByTypeLocked(ctx interface{}, userID interface{}, grantType interface{}, tx interface{}) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	return &MockGrantManager_GetActiveGrantsByTypeLocked_Call{Call: _e.mock.On("GetActiveGrantsByTypeLocked", ctx, userID, grantType, tx)}
}

func (_c *MockGrantManager_GetActiveGrantsByTypeLocked_Call) Run(run func(ctx context.Context, userID uint, grantType GrantType, tx *gorm.DB)) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 GrantType
		if args[2] != nil {
			arg2 = args[2].(GrantType)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByTypeLocked_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByTypeLocked_Call) RunAndReturn(run func(ctx context.Context, userID uint, grantType GrantType, tx *gorm.DB) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsLocked provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsLocked(ctx context.Context, userID uint, tx *gorm.DB) ([]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsLocked")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *gorm.DB) ([]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *gorm.DB) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, userID, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsLocked'
type MockGrantManager_GetActiveGrantsLocked_Call struct {
	*mock.Call
}

// GetActiveGrantsLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) GetActiveGrantsLocked(ctx interface{}, userID interface{}, tx interface{}) *MockGrantManager_GetActiveGrantsLocked_Call {
	return &MockGrantManager_GetActiveGrantsLocked_Call{Call: _e.mock.On("GetActiveGrantsLocked", ctx, userID, tx)}
}

func (_c *MockGrantManager_GetActiveGrantsLocked_Call) Run(run func(ctx context.Context, userID uint, tx *gorm.DB)) *MockGrantManager_GetActiveGrantsLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsLocked_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsLocked_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsLocked_Call) RunAndReturn(run func(ctx context.Context, userID uint, tx *gorm.DB) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsLocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiringGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetExpiringGrants(ctx context.Context, expiryWindow time.Duration) ([]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, expiryWindow)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringGrants")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) ([]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, expiryWindow)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, expiryWindow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, expiryWindow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetExpiringGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiringGrants'
type MockGrantManager_GetExpiringGrants_Call struct {
	*mock.Call
}

// GetExpiringGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - expiryWindow time.Duration
func (_e *MockGrantManager_Expecter) GetExpiringGrants(ctx interface{}, expiryWindow interface{}) *MockGrantManager_GetExpiringGrants_Call {
	return &MockGrantManager_GetExpiringGrants_Call{Call: _e.mock.On("GetExpiringGrants", ctx, expiryWindow)}
}

func (_c *MockGrantManager_GetExpiringGrants_Call) Run(run func(ctx context.Context, expiryWindow time.Duration)) *MockGrantManager_GetExpiringGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetExpiringGrants_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetExpiringGrants_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetExpiringGrants_Call) RunAndReturn(run func(ctx context.Context, expiryWindow time.Duration) ([]*AllowanceGrant, error)) *MockGrantManager_GetExpiringGrants_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiringGrantsForUser provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetExpiringGrantsForUser(ctx context.Context, userID uint, window time.Duration) ([]*AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID, window)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringGrantsForUser")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, time.Duration) ([]*AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID, window)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, time.Duration) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID, window)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetExpiringGrantsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiringGrantsForUser'
type MockGrantManager_GetExpiringGrantsForUser_Call struct {
	*mock.Call
}

// GetExpiringGrantsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - window time.Duration
func (_e *MockGrantManager_Expecter) GetExpiringGrantsForUser(ctx interface{}, userID interface{}, window interface{}) *MockGrantManager_GetExpiringGrantsForUser_Call {
	return &MockGrantManager_GetExpiringGrantsForUser_Call{Call: _e.mock.On("GetExpiringGrantsForUser", ctx, userID, window)}
}

func (_c *MockGrantManager_GetExpiringGrantsForUser_Call) Run(run func(ctx context.Context, userID uint, window time.Duration)) *MockGrantManager_GetExpiringGrantsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetExpiringGrantsForUser_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetExpiringGrantsForUser_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetExpiringGrantsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, window time.Duration) ([]*AllowanceGrant, error)) *MockGrantManager_GetExpiringGrantsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrantByID provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetGrantByID(ctx context.Context, grantID uint) (*AllowanceGrant, error) {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for GetGrantByID")
	}

	var r0 *AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*AllowanceGrant, error)); ok {
		return returnFunc(ctx, grantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *AllowanceGrant); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, grantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetGrantByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrantByID'
type MockGrantManager_GetGrantByID_Call struct {
	*mock.Call
}

// GetGrantByID is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID uint
func (_e *MockGrantManager_Expecter) GetGrantByID(ctx interface{}, grantID interface{}) *MockGrantManager_GetGrantByID_Call {
	return &MockGrantManager_GetGrantByID_Call{Call: _e.mock.On("GetGrantByID", ctx, grantID)}
}

func (_c *MockGrantManager_GetGrantByID_Call) Run(run func(ctx context.Context, grantID uint)) *MockGrantManager_GetGrantByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetGrantByID_Call) Return(v *AllowanceGrant, err error) *MockGrantManager_GetGrantByID_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockGrantManager_GetGrantByID_Call) RunAndReturn(run func(ctx context.Context, grantID uint) (*AllowanceGrant, error)) *MockGrantManager_GetGrantByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) ListGrants(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*AllowanceGrant, int64, error) {
	ret := _mock.Called(ctx, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListGrants")
	}

	var r0 []*AllowanceGrant
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*AllowanceGrant, int64, error)); ok {
		return returnFunc(ctx, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*AllowanceGrant); ok {
		r0 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGrantManager_ListGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrants'
type MockGrantManager_ListGrants_Call struct {
	*mock.Call
}

// ListGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockGrantManager_Expecter) ListGrants(ctx interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockGrantManager_ListGrants_Call {
	return &MockGrantManager_ListGrants_Call{Call: _e.mock.On("ListGrants", ctx, filters, sorts, pagination)}
}

func (_c *MockGrantManager_ListGrants_Call) Run(run func(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockGrantManager_ListGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []queryutil.Sort
		if args[2] != nil {
			arg2 = args[2].([]queryutil.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrantManager_ListGrants_Call) Return(vs []*AllowanceGrant, n int64, err error) *MockGrantManager_ListGrants_Call {
	_c.Call.Return(vs, n, err)
	return _c
}

func (_c *MockGrantManager_ListGrants_Call) RunAndReturn(run func(ctx context.Context, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*AllowanceGrant, int64, error)) *MockGrantManager_ListGrants_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAllowanceGrant provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) UpdateAllowanceGrant(ctx context.Context, grant *AllowanceGrant) error {
	ret := _mock.Called(ctx, grant)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllowanceGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AllowanceGrant) error); ok {
		r0 = returnFunc(ctx, grant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantManager_UpdateAllowanceGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAllowanceGrant'
type MockGrantManager_UpdateAllowanceGrant_Call struct {
	*mock.Call
}

// UpdateAllowanceGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - grant *AllowanceGrant
func (_e *MockGrantManager_Expecter) UpdateAllowanceGrant(ctx interface{}, grant interface{}) *MockGrantManager_UpdateAllowanceGrant_Call {
	return &MockGrantManager_UpdateAllowanceGrant_Call{Call: _e.mock.On("UpdateAllowanceGrant", ctx, grant)}
}

func (_c *MockGrantManager_UpdateAllowanceGrant_Call) Run(run func(ctx context.Context, grant *AllowanceGrant)) *MockGrantManager_UpdateAllowanceGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AllowanceGrant
		if args[1] != nil {
			arg1 = args[1].(*AllowanceGrant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_UpdateAllowanceGrant_Call) Return(err error) *MockGrantManager_UpdateAllowanceGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantManager_UpdateAllowanceGrant_Call) RunAndReturn(run func(ctx context.Context, grant *AllowanceGrant) error) *MockGrantManager_UpdateAllowanceGrant_Call {
	_c.Call.Return(run)
	return _c
}
