// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPolicyEnforcer creates a new instance of MockPolicyEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyEnforcer {
	mock := &MockPolicyEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPolicyEnforcer is an autogenerated mock type for the PolicyEnforcer type
type MockPolicyEnforcer struct {
	mock.Mock
}

type MockPolicyEnforcer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyEnforcer) EXPECT() *MockPolicyEnforcer_Expecter {
	return &MockPolicyEnforcer_Expecter{mock: &_m.Mock}
}

// CheckDownloadQuota provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) CheckDownloadQuota(config *UserQuotaConfig, requestedBytes uint64) (QuotaCheckResult, error) {
	ret := _mock.Called(config, requestedBytes)

	if len(ret) == 0 {
		panic("no return value specified for CheckDownloadQuota")
	}

	var r0 QuotaCheckResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*UserQuotaConfig, uint64) (QuotaCheckResult, error)); ok {
		return returnFunc(config, requestedBytes)
	}
	if returnFunc, ok := ret.Get(0).(func(*UserQuotaConfig, uint64) QuotaCheckResult); ok {
		r0 = returnFunc(config, requestedBytes)
	} else {
		r0 = ret.Get(0).(QuotaCheckResult)
	}
	if returnFunc, ok := ret.Get(1).(func(*UserQuotaConfig, uint64) error); ok {
		r1 = returnFunc(config, requestedBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyEnforcer_CheckDownloadQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDownloadQuota'
type MockPolicyEnforcer_CheckDownloadQuota_Call struct {
	*mock.Call
}

// CheckDownloadQuota is a helper method to define mock.On call
//   - config *UserQuotaConfig
//   - requestedBytes uint64
func (_e *MockPolicyEnforcer_Expecter) CheckDownloadQuota(config interface{}, requestedBytes interface{}) *MockPolicyEnforcer_CheckDownloadQuota_Call {
	return &MockPolicyEnforcer_CheckDownloadQuota_Call{Call: _e.mock.On("CheckDownloadQuota", config, requestedBytes)}
}

func (_c *MockPolicyEnforcer_CheckDownloadQuota_Call) Run(run func(config *UserQuotaConfig, requestedBytes uint64)) *MockPolicyEnforcer_CheckDownloadQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *UserQuotaConfig
		if args[0] != nil {
			arg0 = args[0].(*UserQuotaConfig)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_CheckDownloadQuota_Call) Return(quotaCheckResult QuotaCheckResult, err error) *MockPolicyEnforcer_CheckDownloadQuota_Call {
	_c.Call.Return(quotaCheckResult, err)
	return _c
}

func (_c *MockPolicyEnforcer_CheckDownloadQuota_Call) RunAndReturn(run func(config *UserQuotaConfig, requestedBytes uint64) (QuotaCheckResult, error)) *MockPolicyEnforcer_CheckDownloadQuota_Call {
	_c.Call.Return(run)
	return _c
}

// CheckStorageQuota provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) CheckStorageQuota(config *UserQuotaConfig, requestedBytes uint64) (QuotaCheckResult, error) {
	ret := _mock.Called(config, requestedBytes)

	if len(ret) == 0 {
		panic("no return value specified for CheckStorageQuota")
	}

	var r0 QuotaCheckResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*UserQuotaConfig, uint64) (QuotaCheckResult, error)); ok {
		return returnFunc(config, requestedBytes)
	}
	if returnFunc, ok := ret.Get(0).(func(*UserQuotaConfig, uint64) QuotaCheckResult); ok {
		r0 = returnFunc(config, requestedBytes)
	} else {
		r0 = ret.Get(0).(QuotaCheckResult)
	}
	if returnFunc, ok := ret.Get(1).(func(*UserQuotaConfig, uint64) error); ok {
		r1 = returnFunc(config, requestedBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyEnforcer_CheckStorageQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckStorageQuota'
type MockPolicyEnforcer_CheckStorageQuota_Call struct {
	*mock.Call
}

// CheckStorageQuota is a helper method to define mock.On call
//   - config *UserQuotaConfig
//   - requestedBytes uint64
func (_e *MockPolicyEnforcer_Expecter) CheckStorageQuota(config interface{}, requestedBytes interface{}) *MockPolicyEnforcer_CheckStorageQuota_Call {
	return &MockPolicyEnforcer_CheckStorageQuota_Call{Call: _e.mock.On("CheckStorageQuota", config, requestedBytes)}
}

func (_c *MockPolicyEnforcer_CheckStorageQuota_Call) Run(run func(config *UserQuotaConfig, requestedBytes uint64)) *MockPolicyEnforcer_CheckStorageQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *UserQuotaConfig
		if args[0] != nil {
			arg0 = args[0].(*UserQuotaConfig)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_CheckStorageQuota_Call) Return(quotaCheckResult QuotaCheckResult, err error) *MockPolicyEnforcer_CheckStorageQuota_Call {
	_c.Call.Return(quotaCheckResult, err)
	return _c
}

func (_c *MockPolicyEnforcer_CheckStorageQuota_Call) RunAndReturn(run func(config *UserQuotaConfig, requestedBytes uint64) (QuotaCheckResult, error)) *MockPolicyEnforcer_CheckStorageQuota_Call {
	_c.Call.Return(run)
	return _c
}

// CheckUploadQuota provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) CheckUploadQuota(config *UserQuotaConfig, requestedBytes uint64) (QuotaCheckResult, error) {
	ret := _mock.Called(config, requestedBytes)

	if len(ret) == 0 {
		panic("no return value specified for CheckUploadQuota")
	}

	var r0 QuotaCheckResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*UserQuotaConfig, uint64) (QuotaCheckResult, error)); ok {
		return returnFunc(config, requestedBytes)
	}
	if returnFunc, ok := ret.Get(0).(func(*UserQuotaConfig, uint64) QuotaCheckResult); ok {
		r0 = returnFunc(config, requestedBytes)
	} else {
		r0 = ret.Get(0).(QuotaCheckResult)
	}
	if returnFunc, ok := ret.Get(1).(func(*UserQuotaConfig, uint64) error); ok {
		r1 = returnFunc(config, requestedBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyEnforcer_CheckUploadQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUploadQuota'
type MockPolicyEnforcer_CheckUploadQuota_Call struct {
	*mock.Call
}

// CheckUploadQuota is a helper method to define mock.On call
//   - config *UserQuotaConfig
//   - requestedBytes uint64
func (_e *MockPolicyEnforcer_Expecter) CheckUploadQuota(config interface{}, requestedBytes interface{}) *MockPolicyEnforcer_CheckUploadQuota_Call {
	return &MockPolicyEnforcer_CheckUploadQuota_Call{Call: _e.mock.On("CheckUploadQuota", config, requestedBytes)}
}

func (_c *MockPolicyEnforcer_CheckUploadQuota_Call) Run(run func(config *UserQuotaConfig, requestedBytes uint64)) *MockPolicyEnforcer_CheckUploadQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *UserQuotaConfig
		if args[0] != nil {
			arg0 = args[0].(*UserQuotaConfig)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_CheckUploadQuota_Call) Return(quotaCheckResult QuotaCheckResult, err error) *MockPolicyEnforcer_CheckUploadQuota_Call {
	_c.Call.Return(quotaCheckResult, err)
	return _c
}

func (_c *MockPolicyEnforcer_CheckUploadQuota_Call) RunAndReturn(run func(config *UserQuotaConfig, requestedBytes uint64) (QuotaCheckResult, error)) *MockPolicyEnforcer_CheckUploadQuota_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUsage provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) GetCurrentUsage(userID uint) (*Usage, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUsage")
	}

	var r0 *Usage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Usage, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Usage); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Usage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyEnforcer_GetCurrentUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUsage'
type MockPolicyEnforcer_GetCurrentUsage_Call struct {
	*mock.Call
}

// GetCurrentUsage is a helper method to define mock.On call
//   - userID uint
func (_e *MockPolicyEnforcer_Expecter) GetCurrentUsage(userID interface{}) *MockPolicyEnforcer_GetCurrentUsage_Call {
	return &MockPolicyEnforcer_GetCurrentUsage_Call{Call: _e.mock.On("GetCurrentUsage", userID)}
}

func (_c *MockPolicyEnforcer_GetCurrentUsage_Call) Run(run func(userID uint)) *MockPolicyEnforcer_GetCurrentUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_GetCurrentUsage_Call) Return(usage *Usage, err error) *MockPolicyEnforcer_GetCurrentUsage_Call {
	_c.Call.Return(usage, err)
	return _c
}

func (_c *MockPolicyEnforcer_GetCurrentUsage_Call) RunAndReturn(run func(userID uint) (*Usage, error)) *MockPolicyEnforcer_GetCurrentUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetailedUsage provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) GetDetailedUsage(userID uint, start time.Time, end time.Time) ([]*UserUsageDetail, error) {
	ret := _mock.Called(userID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedUsage")
	}

	var r0 []*UserUsageDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, time.Time, time.Time) ([]*UserUsageDetail, error)); ok {
		return returnFunc(userID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, time.Time, time.Time) []*UserUsageDetail); ok {
		r0 = returnFunc(userID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*UserUsageDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, time.Time, time.Time) error); ok {
		r1 = returnFunc(userID, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyEnforcer_GetDetailedUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailedUsage'
type MockPolicyEnforcer_GetDetailedUsage_Call struct {
	*mock.Call
}

// GetDetailedUsage is a helper method to define mock.On call
//   - userID uint
//   - start time.Time
//   - end time.Time
func (_e *MockPolicyEnforcer_Expecter) GetDetailedUsage(userID interface{}, start interface{}, end interface{}) *MockPolicyEnforcer_GetDetailedUsage_Call {
	return &MockPolicyEnforcer_GetDetailedUsage_Call{Call: _e.mock.On("GetDetailedUsage", userID, start, end)}
}

func (_c *MockPolicyEnforcer_GetDetailedUsage_Call) Run(run func(userID uint, start time.Time, end time.Time)) *MockPolicyEnforcer_GetDetailedUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_GetDetailedUsage_Call) Return(vs []*UserUsageDetail, err error) *MockPolicyEnforcer_GetDetailedUsage_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockPolicyEnforcer_GetDetailedUsage_Call) RunAndReturn(run func(userID uint, start time.Time, end time.Time) ([]*UserUsageDetail, error)) *MockPolicyEnforcer_GetDetailedUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsageHistory provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) GetUsageHistory(userID uint, period int, usageType UsageType) ([]*UsagePoint, error) {
	ret := _mock.Called(userID, period, usageType)

	if len(ret) == 0 {
		panic("no return value specified for GetUsageHistory")
	}

	var r0 []*UsagePoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, int, UsageType) ([]*UsagePoint, error)); ok {
		return returnFunc(userID, period, usageType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, int, UsageType) []*UsagePoint); ok {
		r0 = returnFunc(userID, period, usageType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*UsagePoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, int, UsageType) error); ok {
		r1 = returnFunc(userID, period, usageType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyEnforcer_GetUsageHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsageHistory'
type MockPolicyEnforcer_GetUsageHistory_Call struct {
	*mock.Call
}

// GetUsageHistory is a helper method to define mock.On call
//   - userID uint
//   - period int
//   - usageType UsageType
func (_e *MockPolicyEnforcer_Expecter) GetUsageHistory(userID interface{}, period interface{}, usageType interface{}) *MockPolicyEnforcer_GetUsageHistory_Call {
	return &MockPolicyEnforcer_GetUsageHistory_Call{Call: _e.mock.On("GetUsageHistory", userID, period, usageType)}
}

func (_c *MockPolicyEnforcer_GetUsageHistory_Call) Run(run func(userID uint, period int, usageType UsageType)) *MockPolicyEnforcer_GetUsageHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_GetUsageHistory_Call) Return(usagePoints []*UsagePoint, err error) *MockPolicyEnforcer_GetUsageHistory_Call {
	_c.Call.Return(usagePoints, err)
	return _c
}

func (_c *MockPolicyEnforcer_GetUsageHistory_Call) RunAndReturn(run func(userID uint, period int, usageType UsageType) ([]*UsagePoint, error)) *MockPolicyEnforcer_GetUsageHistory_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDownload provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) RecordDownload(userID uint, uploadID uint, bytes uint64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, uint64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyEnforcer_RecordDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDownload'
type MockPolicyEnforcer_RecordDownload_Call struct {
	*mock.Call
}

// RecordDownload is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes uint64
//   - ip string
func (_e *MockPolicyEnforcer_Expecter) RecordDownload(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockPolicyEnforcer_RecordDownload_Call {
	return &MockPolicyEnforcer_RecordDownload_Call{Call: _e.mock.On("RecordDownload", userID, uploadID, bytes, ip)}
}

func (_c *MockPolicyEnforcer_RecordDownload_Call) Run(run func(userID uint, uploadID uint, bytes uint64, ip string)) *MockPolicyEnforcer_RecordDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_RecordDownload_Call) Return(err error) *MockPolicyEnforcer_RecordDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyEnforcer_RecordDownload_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes uint64, ip string) error) *MockPolicyEnforcer_RecordDownload_Call {
	_c.Call.Return(run)
	return _c
}

// RecordStorageChange provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) RecordStorageChange(userID uint, uploadID uint, bytes int64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordStorageChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, int64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyEnforcer_RecordStorageChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStorageChange'
type MockPolicyEnforcer_RecordStorageChange_Call struct {
	*mock.Call
}

// RecordStorageChange is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes int64
//   - ip string
func (_e *MockPolicyEnforcer_Expecter) RecordStorageChange(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockPolicyEnforcer_RecordStorageChange_Call {
	return &MockPolicyEnforcer_RecordStorageChange_Call{Call: _e.mock.On("RecordStorageChange", userID, uploadID, bytes, ip)}
}

func (_c *MockPolicyEnforcer_RecordStorageChange_Call) Run(run func(userID uint, uploadID uint, bytes int64, ip string)) *MockPolicyEnforcer_RecordStorageChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_RecordStorageChange_Call) Return(err error) *MockPolicyEnforcer_RecordStorageChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyEnforcer_RecordStorageChange_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes int64, ip string) error) *MockPolicyEnforcer_RecordStorageChange_Call {
	_c.Call.Return(run)
	return _c
}

// RecordUpload provides a mock function for the type MockPolicyEnforcer
func (_mock *MockPolicyEnforcer) RecordUpload(userID uint, uploadID uint, bytes uint64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, uint64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyEnforcer_RecordUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUpload'
type MockPolicyEnforcer_RecordUpload_Call struct {
	*mock.Call
}

// RecordUpload is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes uint64
//   - ip string
func (_e *MockPolicyEnforcer_Expecter) RecordUpload(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockPolicyEnforcer_RecordUpload_Call {
	return &MockPolicyEnforcer_RecordUpload_Call{Call: _e.mock.On("RecordUpload", userID, uploadID, bytes, ip)}
}

func (_c *MockPolicyEnforcer_RecordUpload_Call) Run(run func(userID uint, uploadID uint, bytes uint64, ip string)) *MockPolicyEnforcer_RecordUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyEnforcer_RecordUpload_Call) Return(err error) *MockPolicyEnforcer_RecordUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyEnforcer_RecordUpload_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes uint64, ip string) error) *MockPolicyEnforcer_RecordUpload_Call {
	_c.Call.Return(run)
	return _c
}
