// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockGrantManager creates a new instance of MockGrantManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrantManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrantManager {
	mock := &MockGrantManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrantManager is an autogenerated mock type for the GrantManager type
type MockGrantManager struct {
	mock.Mock
}

type MockGrantManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrantManager) EXPECT() *MockGrantManager_Expecter {
	return &MockGrantManager_Expecter{mock: &_m.Mock}
}

// CalculateAvailableBytes provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) CalculateAvailableBytes(grants []*AllowanceGrant) uint64 {
	ret := _mock.Called(grants)

	if len(ret) == 0 {
		panic("no return value specified for CalculateAvailableBytes")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func([]*AllowanceGrant) uint64); ok {
		r0 = returnFunc(grants)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// MockGrantManager_CalculateAvailableBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateAvailableBytes'
type MockGrantManager_CalculateAvailableBytes_Call struct {
	*mock.Call
}

// CalculateAvailableBytes is a helper method to define mock.On call
//   - grants []*AllowanceGrant
func (_e *MockGrantManager_Expecter) CalculateAvailableBytes(grants interface{}) *MockGrantManager_CalculateAvailableBytes_Call {
	return &MockGrantManager_CalculateAvailableBytes_Call{Call: _e.mock.On("CalculateAvailableBytes", grants)}
}

func (_c *MockGrantManager_CalculateAvailableBytes_Call) Run(run func(grants []*AllowanceGrant)) *MockGrantManager_CalculateAvailableBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*AllowanceGrant
		if args[0] != nil {
			arg0 = args[0].([]*AllowanceGrant)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrantManager_CalculateAvailableBytes_Call) Return(v uint64) *MockGrantManager_CalculateAvailableBytes_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockGrantManager_CalculateAvailableBytes_Call) RunAndReturn(run func(grants []*AllowanceGrant) uint64) *MockGrantManager_CalculateAvailableBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeFromGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) ConsumeFromGrants(userID uint, grantType GrantType, bytes uint64, usageDetailID uint, tx *gorm.DB) ([]*AllowanceConsumption, error) {
	ret := _mock.Called(userID, grantType, bytes, usageDetailID, tx)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeFromGrants")
	}

	var r0 []*AllowanceConsumption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, GrantType, uint64, uint, *gorm.DB) ([]*AllowanceConsumption, error)); ok {
		return returnFunc(userID, grantType, bytes, usageDetailID, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, GrantType, uint64, uint, *gorm.DB) []*AllowanceConsumption); ok {
		r0 = returnFunc(userID, grantType, bytes, usageDetailID, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceConsumption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, GrantType, uint64, uint, *gorm.DB) error); ok {
		r1 = returnFunc(userID, grantType, bytes, usageDetailID, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_ConsumeFromGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeFromGrants'
type MockGrantManager_ConsumeFromGrants_Call struct {
	*mock.Call
}

// ConsumeFromGrants is a helper method to define mock.On call
//   - userID uint
//   - grantType GrantType
//   - bytes uint64
//   - usageDetailID uint
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) ConsumeFromGrants(userID interface{}, grantType interface{}, bytes interface{}, usageDetailID interface{}, tx interface{}) *MockGrantManager_ConsumeFromGrants_Call {
	return &MockGrantManager_ConsumeFromGrants_Call{Call: _e.mock.On("ConsumeFromGrants", userID, grantType, bytes, usageDetailID, tx)}
}

func (_c *MockGrantManager_ConsumeFromGrants_Call) Run(run func(userID uint, grantType GrantType, bytes uint64, usageDetailID uint, tx *gorm.DB)) *MockGrantManager_ConsumeFromGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 GrantType
		if args[1] != nil {
			arg1 = args[1].(GrantType)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		var arg4 *gorm.DB
		if args[4] != nil {
			arg4 = args[4].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGrantManager_ConsumeFromGrants_Call) Return(vs []*AllowanceConsumption, err error) *MockGrantManager_ConsumeFromGrants_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_ConsumeFromGrants_Call) RunAndReturn(run func(userID uint, grantType GrantType, bytes uint64, usageDetailID uint, tx *gorm.DB) ([]*AllowanceConsumption, error)) *MockGrantManager_ConsumeFromGrants_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAllowanceGrant provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) CreateAllowanceGrant(userID uint, grant *AllowanceGrant) error {
	ret := _mock.Called(userID, grant)

	if len(ret) == 0 {
		panic("no return value specified for CreateAllowanceGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, *AllowanceGrant) error); ok {
		r0 = returnFunc(userID, grant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantManager_CreateAllowanceGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAllowanceGrant'
type MockGrantManager_CreateAllowanceGrant_Call struct {
	*mock.Call
}

// CreateAllowanceGrant is a helper method to define mock.On call
//   - userID uint
//   - grant *AllowanceGrant
func (_e *MockGrantManager_Expecter) CreateAllowanceGrant(userID interface{}, grant interface{}) *MockGrantManager_CreateAllowanceGrant_Call {
	return &MockGrantManager_CreateAllowanceGrant_Call{Call: _e.mock.On("CreateAllowanceGrant", userID, grant)}
}

func (_c *MockGrantManager_CreateAllowanceGrant_Call) Run(run func(userID uint, grant *AllowanceGrant)) *MockGrantManager_CreateAllowanceGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *AllowanceGrant
		if args[1] != nil {
			arg1 = args[1].(*AllowanceGrant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_CreateAllowanceGrant_Call) Return(err error) *MockGrantManager_CreateAllowanceGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantManager_CreateAllowanceGrant_Call) RunAndReturn(run func(userID uint, grant *AllowanceGrant) error) *MockGrantManager_CreateAllowanceGrant_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateGrant provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) DeactivateGrant(grantID uint) error {
	ret := _mock.Called(grantID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(grantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantManager_DeactivateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateGrant'
type MockGrantManager_DeactivateGrant_Call struct {
	*mock.Call
}

// DeactivateGrant is a helper method to define mock.On call
//   - grantID uint
func (_e *MockGrantManager_Expecter) DeactivateGrant(grantID interface{}) *MockGrantManager_DeactivateGrant_Call {
	return &MockGrantManager_DeactivateGrant_Call{Call: _e.mock.On("DeactivateGrant", grantID)}
}

func (_c *MockGrantManager_DeactivateGrant_Call) Run(run func(grantID uint)) *MockGrantManager_DeactivateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrantManager_DeactivateGrant_Call) Return(err error) *MockGrantManager_DeactivateGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantManager_DeactivateGrant_Call) RunAndReturn(run func(grantID uint) error) *MockGrantManager_DeactivateGrant_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrants(userID uint) ([]*AllowanceGrant, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrants")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]*AllowanceGrant, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []*AllowanceGrant); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrants'
type MockGrantManager_GetActiveGrants_Call struct {
	*mock.Call
}

// GetActiveGrants is a helper method to define mock.On call
//   - userID uint
func (_e *MockGrantManager_Expecter) GetActiveGrants(userID interface{}) *MockGrantManager_GetActiveGrants_Call {
	return &MockGrantManager_GetActiveGrants_Call{Call: _e.mock.On("GetActiveGrants", userID)}
}

func (_c *MockGrantManager_GetActiveGrants_Call) Run(run func(userID uint)) *MockGrantManager_GetActiveGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrants_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrants_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrants_Call) RunAndReturn(run func(userID uint) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrants_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsByType provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsByType(userID uint, grantType GrantType) ([]*AllowanceGrant, error) {
	ret := _mock.Called(userID, grantType)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsByType")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, GrantType) ([]*AllowanceGrant, error)); ok {
		return returnFunc(userID, grantType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, GrantType) []*AllowanceGrant); ok {
		r0 = returnFunc(userID, grantType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, GrantType) error); ok {
		r1 = returnFunc(userID, grantType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsByType'
type MockGrantManager_GetActiveGrantsByType_Call struct {
	*mock.Call
}

// GetActiveGrantsByType is a helper method to define mock.On call
//   - userID uint
//   - grantType GrantType
func (_e *MockGrantManager_Expecter) GetActiveGrantsByType(userID interface{}, grantType interface{}) *MockGrantManager_GetActiveGrantsByType_Call {
	return &MockGrantManager_GetActiveGrantsByType_Call{Call: _e.mock.On("GetActiveGrantsByType", userID, grantType)}
}

func (_c *MockGrantManager_GetActiveGrantsByType_Call) Run(run func(userID uint, grantType GrantType)) *MockGrantManager_GetActiveGrantsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 GrantType
		if args[1] != nil {
			arg1 = args[1].(GrantType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByType_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsByType_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByType_Call) RunAndReturn(run func(userID uint, grantType GrantType) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsByTypeLocked provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsByTypeLocked(userID uint, grantType GrantType, tx *gorm.DB) ([]*AllowanceGrant, error) {
	ret := _mock.Called(userID, grantType, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsByTypeLocked")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, GrantType, *gorm.DB) ([]*AllowanceGrant, error)); ok {
		return returnFunc(userID, grantType, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, GrantType, *gorm.DB) []*AllowanceGrant); ok {
		r0 = returnFunc(userID, grantType, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, GrantType, *gorm.DB) error); ok {
		r1 = returnFunc(userID, grantType, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsByTypeLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsByTypeLocked'
type MockGrantManager_GetActiveGrantsByTypeLocked_Call struct {
	*mock.Call
}

// GetActiveGrantsByTypeLocked is a helper method to define mock.On call
//   - userID uint
//   - grantType GrantType
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) GetActiveGrantsByTypeLocked(userID interface{}, grantType interface{}, tx interface{}) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	return &MockGrantManager_GetActiveGrantsByTypeLocked_Call{Call: _e.mock.On("GetActiveGrantsByTypeLocked", userID, grantType, tx)}
}

func (_c *MockGrantManager_GetActiveGrantsByTypeLocked_Call) Run(run func(userID uint, grantType GrantType, tx *gorm.DB)) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 GrantType
		if args[1] != nil {
			arg1 = args[1].(GrantType)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByTypeLocked_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsByTypeLocked_Call) RunAndReturn(run func(userID uint, grantType GrantType, tx *gorm.DB) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsByTypeLocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGrantsLocked provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetActiveGrantsLocked(userID uint, tx *gorm.DB) ([]*AllowanceGrant, error) {
	ret := _mock.Called(userID, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGrantsLocked")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, *gorm.DB) ([]*AllowanceGrant, error)); ok {
		return returnFunc(userID, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, *gorm.DB) []*AllowanceGrant); ok {
		r0 = returnFunc(userID, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, *gorm.DB) error); ok {
		r1 = returnFunc(userID, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetActiveGrantsLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGrantsLocked'
type MockGrantManager_GetActiveGrantsLocked_Call struct {
	*mock.Call
}

// GetActiveGrantsLocked is a helper method to define mock.On call
//   - userID uint
//   - tx *gorm.DB
func (_e *MockGrantManager_Expecter) GetActiveGrantsLocked(userID interface{}, tx interface{}) *MockGrantManager_GetActiveGrantsLocked_Call {
	return &MockGrantManager_GetActiveGrantsLocked_Call{Call: _e.mock.On("GetActiveGrantsLocked", userID, tx)}
}

func (_c *MockGrantManager_GetActiveGrantsLocked_Call) Run(run func(userID uint, tx *gorm.DB)) *MockGrantManager_GetActiveGrantsLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsLocked_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetActiveGrantsLocked_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetActiveGrantsLocked_Call) RunAndReturn(run func(userID uint, tx *gorm.DB) ([]*AllowanceGrant, error)) *MockGrantManager_GetActiveGrantsLocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiringGrants provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetExpiringGrants(expiryWindow time.Duration) ([]*AllowanceGrant, error) {
	ret := _mock.Called(expiryWindow)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringGrants")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) ([]*AllowanceGrant, error)); ok {
		return returnFunc(expiryWindow)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Duration) []*AllowanceGrant); ok {
		r0 = returnFunc(expiryWindow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Duration) error); ok {
		r1 = returnFunc(expiryWindow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetExpiringGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiringGrants'
type MockGrantManager_GetExpiringGrants_Call struct {
	*mock.Call
}

// GetExpiringGrants is a helper method to define mock.On call
//   - expiryWindow time.Duration
func (_e *MockGrantManager_Expecter) GetExpiringGrants(expiryWindow interface{}) *MockGrantManager_GetExpiringGrants_Call {
	return &MockGrantManager_GetExpiringGrants_Call{Call: _e.mock.On("GetExpiringGrants", expiryWindow)}
}

func (_c *MockGrantManager_GetExpiringGrants_Call) Run(run func(expiryWindow time.Duration)) *MockGrantManager_GetExpiringGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetExpiringGrants_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetExpiringGrants_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetExpiringGrants_Call) RunAndReturn(run func(expiryWindow time.Duration) ([]*AllowanceGrant, error)) *MockGrantManager_GetExpiringGrants_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiringGrantsForUser provides a mock function for the type MockGrantManager
func (_mock *MockGrantManager) GetExpiringGrantsForUser(userID uint, window time.Duration) ([]*AllowanceGrant, error) {
	ret := _mock.Called(userID, window)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringGrantsForUser")
	}

	var r0 []*AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, time.Duration) ([]*AllowanceGrant, error)); ok {
		return returnFunc(userID, window)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, time.Duration) []*AllowanceGrant); ok {
		r0 = returnFunc(userID, window)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, time.Duration) error); ok {
		r1 = returnFunc(userID, window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantManager_GetExpiringGrantsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiringGrantsForUser'
type MockGrantManager_GetExpiringGrantsForUser_Call struct {
	*mock.Call
}

// GetExpiringGrantsForUser is a helper method to define mock.On call
//   - userID uint
//   - window time.Duration
func (_e *MockGrantManager_Expecter) GetExpiringGrantsForUser(userID interface{}, window interface{}) *MockGrantManager_GetExpiringGrantsForUser_Call {
	return &MockGrantManager_GetExpiringGrantsForUser_Call{Call: _e.mock.On("GetExpiringGrantsForUser", userID, window)}
}

func (_c *MockGrantManager_GetExpiringGrantsForUser_Call) Run(run func(userID uint, window time.Duration)) *MockGrantManager_GetExpiringGrantsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantManager_GetExpiringGrantsForUser_Call) Return(vs []*AllowanceGrant, err error) *MockGrantManager_GetExpiringGrantsForUser_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrantManager_GetExpiringGrantsForUser_Call) RunAndReturn(run func(userID uint, window time.Duration) ([]*AllowanceGrant, error)) *MockGrantManager_GetExpiringGrantsForUser_Call {
	_c.Call.Return(run)
	return _c
}
