// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsageManager creates a new instance of MockUsageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsageManager {
	mock := &MockUsageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsageManager is an autogenerated mock type for the UsageManager type
type MockUsageManager struct {
	mock.Mock
}

type MockUsageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsageManager) EXPECT() *MockUsageManager_Expecter {
	return &MockUsageManager_Expecter{mock: &_m.Mock}
}

// RecordDownload provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordDownload(userID uint, uploadID uint, bytes uint64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, uint64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDownload'
type MockUsageManager_RecordDownload_Call struct {
	*mock.Call
}

// RecordDownload is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes uint64
//   - ip string
func (_e *MockUsageManager_Expecter) RecordDownload(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockUsageManager_RecordDownload_Call {
	return &MockUsageManager_RecordDownload_Call{Call: _e.mock.On("RecordDownload", userID, uploadID, bytes, ip)}
}

func (_c *MockUsageManager_RecordDownload_Call) Run(run func(userID uint, uploadID uint, bytes uint64, ip string)) *MockUsageManager_RecordDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordDownload_Call) Return(err error) *MockUsageManager_RecordDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordDownload_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes uint64, ip string) error) *MockUsageManager_RecordDownload_Call {
	_c.Call.Return(run)
	return _c
}

// RecordStorageChange provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordStorageChange(userID uint, uploadID uint, bytes int64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordStorageChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, int64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordStorageChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStorageChange'
type MockUsageManager_RecordStorageChange_Call struct {
	*mock.Call
}

// RecordStorageChange is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes int64
//   - ip string
func (_e *MockUsageManager_Expecter) RecordStorageChange(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockUsageManager_RecordStorageChange_Call {
	return &MockUsageManager_RecordStorageChange_Call{Call: _e.mock.On("RecordStorageChange", userID, uploadID, bytes, ip)}
}

func (_c *MockUsageManager_RecordStorageChange_Call) Run(run func(userID uint, uploadID uint, bytes int64, ip string)) *MockUsageManager_RecordStorageChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordStorageChange_Call) Return(err error) *MockUsageManager_RecordStorageChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordStorageChange_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes int64, ip string) error) *MockUsageManager_RecordStorageChange_Call {
	_c.Call.Return(run)
	return _c
}

// RecordUpload provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordUpload(userID uint, uploadID uint, bytes uint64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, uint64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUpload'
type MockUsageManager_RecordUpload_Call struct {
	*mock.Call
}

// RecordUpload is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes uint64
//   - ip string
func (_e *MockUsageManager_Expecter) RecordUpload(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockUsageManager_RecordUpload_Call {
	return &MockUsageManager_RecordUpload_Call{Call: _e.mock.On("RecordUpload", userID, uploadID, bytes, ip)}
}

func (_c *MockUsageManager_RecordUpload_Call) Run(run func(userID uint, uploadID uint, bytes uint64, ip string)) *MockUsageManager_RecordUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordUpload_Call) Return(err error) *MockUsageManager_RecordUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordUpload_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes uint64, ip string) error) *MockUsageManager_RecordUpload_Call {
	_c.Call.Return(run)
	return _c
}
