// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-quota/internal/db/models"
)

// NewMockLimitResolver creates a new instance of MockLimitResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimitResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimitResolver {
	mock := &MockLimitResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLimitResolver is an autogenerated mock type for the LimitResolver type
type MockLimitResolver struct {
	mock.Mock
}

type MockLimitResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimitResolver) EXPECT() *MockLimitResolver_Expecter {
	return &MockLimitResolver_Expecter{mock: &_m.Mock}
}

// ResolveEffectiveLimits provides a mock function for the type MockLimitResolver
func (_mock *MockLimitResolver) ResolveEffectiveLimits(ctx context.Context, config *models.UserQuotaConfig, policy models.EnforcementPolicy) (*EffectiveLimits, error) {
	ret := _mock.Called(ctx, config, policy)

	if len(ret) == 0 {
		panic("no return value specified for ResolveEffectiveLimits")
	}

	var r0 *EffectiveLimits
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserQuotaConfig, models.EnforcementPolicy) (*EffectiveLimits, error)); ok {
		return returnFunc(ctx, config, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserQuotaConfig, models.EnforcementPolicy) *EffectiveLimits); ok {
		r0 = returnFunc(ctx, config, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EffectiveLimits)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UserQuotaConfig, models.EnforcementPolicy) error); ok {
		r1 = returnFunc(ctx, config, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLimitResolver_ResolveEffectiveLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveEffectiveLimits'
type MockLimitResolver_ResolveEffectiveLimits_Call struct {
	*mock.Call
}

// ResolveEffectiveLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - config *models.UserQuotaConfig
//   - policy models.EnforcementPolicy
func (_e *MockLimitResolver_Expecter) ResolveEffectiveLimits(ctx interface{}, config interface{}, policy interface{}) *MockLimitResolver_ResolveEffectiveLimits_Call {
	return &MockLimitResolver_ResolveEffectiveLimits_Call{Call: _e.mock.On("ResolveEffectiveLimits", ctx, config, policy)}
}

func (_c *MockLimitResolver_ResolveEffectiveLimits_Call) Run(run func(ctx context.Context, config *models.UserQuotaConfig, policy models.EnforcementPolicy)) *MockLimitResolver_ResolveEffectiveLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UserQuotaConfig
		if args[1] != nil {
			arg1 = args[1].(*models.UserQuotaConfig)
		}
		var arg2 models.EnforcementPolicy
		if args[2] != nil {
			arg2 = args[2].(models.EnforcementPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLimitResolver_ResolveEffectiveLimits_Call) Return(effectiveLimits *EffectiveLimits, err error) *MockLimitResolver_ResolveEffectiveLimits_Call {
	_c.Call.Return(effectiveLimits, err)
	return _c
}

func (_c *MockLimitResolver_ResolveEffectiveLimits_Call) RunAndReturn(run func(ctx context.Context, config *models.UserQuotaConfig, policy models.EnforcementPolicy) (*EffectiveLimits, error)) *MockLimitResolver_ResolveEffectiveLimits_Call {
	_c.Call.Return(run)
	return _c
}
