// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-quota/internal/db/models"
)

// NewMockUsageManager creates a new instance of MockUsageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsageManager {
	mock := &MockUsageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsageManager is an autogenerated mock type for the UsageManager type
type MockUsageManager struct {
	mock.Mock
}

type MockUsageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsageManager) EXPECT() *MockUsageManager_Expecter {
	return &MockUsageManager_Expecter{mock: &_m.Mock}
}

// GetCurrentUsage provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) GetCurrentUsage(userID uint) (*Usage, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUsage")
	}

	var r0 *Usage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Usage, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Usage); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Usage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageManager_GetCurrentUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUsage'
type MockUsageManager_GetCurrentUsage_Call struct {
	*mock.Call
}

// GetCurrentUsage is a helper method to define mock.On call
//   - userID uint
func (_e *MockUsageManager_Expecter) GetCurrentUsage(userID interface{}) *MockUsageManager_GetCurrentUsage_Call {
	return &MockUsageManager_GetCurrentUsage_Call{Call: _e.mock.On("GetCurrentUsage", userID)}
}

func (_c *MockUsageManager_GetCurrentUsage_Call) Run(run func(userID uint)) *MockUsageManager_GetCurrentUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsageManager_GetCurrentUsage_Call) Return(usage *Usage, err error) *MockUsageManager_GetCurrentUsage_Call {
	_c.Call.Return(usage, err)
	return _c
}

func (_c *MockUsageManager_GetCurrentUsage_Call) RunAndReturn(run func(userID uint) (*Usage, error)) *MockUsageManager_GetCurrentUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetailedUsage provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) GetDetailedUsage(userID uint, start time.Time, end time.Time) ([]*UserUsageDetail, error) {
	ret := _mock.Called(userID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedUsage")
	}

	var r0 []*UserUsageDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, time.Time, time.Time) ([]*UserUsageDetail, error)); ok {
		return returnFunc(userID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, time.Time, time.Time) []*UserUsageDetail); ok {
		r0 = returnFunc(userID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*UserUsageDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, time.Time, time.Time) error); ok {
		r1 = returnFunc(userID, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageManager_GetDetailedUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetailedUsage'
type MockUsageManager_GetDetailedUsage_Call struct {
	*mock.Call
}

// GetDetailedUsage is a helper method to define mock.On call
//   - userID uint
//   - start time.Time
//   - end time.Time
func (_e *MockUsageManager_Expecter) GetDetailedUsage(userID interface{}, start interface{}, end interface{}) *MockUsageManager_GetDetailedUsage_Call {
	return &MockUsageManager_GetDetailedUsage_Call{Call: _e.mock.On("GetDetailedUsage", userID, start, end)}
}

func (_c *MockUsageManager_GetDetailedUsage_Call) Run(run func(userID uint, start time.Time, end time.Time)) *MockUsageManager_GetDetailedUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsageManager_GetDetailedUsage_Call) Return(vs []*UserUsageDetail, err error) *MockUsageManager_GetDetailedUsage_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockUsageManager_GetDetailedUsage_Call) RunAndReturn(run func(userID uint, start time.Time, end time.Time) ([]*UserUsageDetail, error)) *MockUsageManager_GetDetailedUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalBytesByType provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) GetTotalBytesByType(userID uint, usageType UsageType) (uint64, error) {
	ret := _mock.Called(userID, usageType)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalBytesByType")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, UsageType) (uint64, error)); ok {
		return returnFunc(userID, usageType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, UsageType) uint64); ok {
		r0 = returnFunc(userID, usageType)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, UsageType) error); ok {
		r1 = returnFunc(userID, usageType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageManager_GetTotalBytesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalBytesByType'
type MockUsageManager_GetTotalBytesByType_Call struct {
	*mock.Call
}

// GetTotalBytesByType is a helper method to define mock.On call
//   - userID uint
//   - usageType UsageType
func (_e *MockUsageManager_Expecter) GetTotalBytesByType(userID interface{}, usageType interface{}) *MockUsageManager_GetTotalBytesByType_Call {
	return &MockUsageManager_GetTotalBytesByType_Call{Call: _e.mock.On("GetTotalBytesByType", userID, usageType)}
}

func (_c *MockUsageManager_GetTotalBytesByType_Call) Run(run func(userID uint, usageType UsageType)) *MockUsageManager_GetTotalBytesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 UsageType
		if args[1] != nil {
			arg1 = args[1].(UsageType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsageManager_GetTotalBytesByType_Call) Return(v uint64, err error) *MockUsageManager_GetTotalBytesByType_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUsageManager_GetTotalBytesByType_Call) RunAndReturn(run func(userID uint, usageType UsageType) (uint64, error)) *MockUsageManager_GetTotalBytesByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsageHistory provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) GetUsageHistory(userID uint, period int, usageType UsageType) ([]*UsagePoint, error) {
	ret := _mock.Called(userID, period, usageType)

	if len(ret) == 0 {
		panic("no return value specified for GetUsageHistory")
	}

	var r0 []*UsagePoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, int, UsageType) ([]*UsagePoint, error)); ok {
		return returnFunc(userID, period, usageType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, int, UsageType) []*UsagePoint); ok {
		r0 = returnFunc(userID, period, usageType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*UsagePoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, int, UsageType) error); ok {
		r1 = returnFunc(userID, period, usageType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageManager_GetUsageHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsageHistory'
type MockUsageManager_GetUsageHistory_Call struct {
	*mock.Call
}

// GetUsageHistory is a helper method to define mock.On call
//   - userID uint
//   - period int
//   - usageType UsageType
func (_e *MockUsageManager_Expecter) GetUsageHistory(userID interface{}, period interface{}, usageType interface{}) *MockUsageManager_GetUsageHistory_Call {
	return &MockUsageManager_GetUsageHistory_Call{Call: _e.mock.On("GetUsageHistory", userID, period, usageType)}
}

func (_c *MockUsageManager_GetUsageHistory_Call) Run(run func(userID uint, period int, usageType UsageType)) *MockUsageManager_GetUsageHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsageManager_GetUsageHistory_Call) Return(usagePoints []*UsagePoint, err error) *MockUsageManager_GetUsageHistory_Call {
	_c.Call.Return(usagePoints, err)
	return _c
}

func (_c *MockUsageManager_GetUsageHistory_Call) RunAndReturn(run func(userID uint, period int, usageType UsageType) ([]*UsagePoint, error)) *MockUsageManager_GetUsageHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserQuotaConfig provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) GetUserQuotaConfig(userID uint) (*models.UserQuotaConfig, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserQuotaConfig")
	}

	var r0 *models.UserQuotaConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.UserQuotaConfig, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.UserQuotaConfig); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserQuotaConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageManager_GetUserQuotaConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserQuotaConfig'
type MockUsageManager_GetUserQuotaConfig_Call struct {
	*mock.Call
}

// GetUserQuotaConfig is a helper method to define mock.On call
//   - userID uint
func (_e *MockUsageManager_Expecter) GetUserQuotaConfig(userID interface{}) *MockUsageManager_GetUserQuotaConfig_Call {
	return &MockUsageManager_GetUserQuotaConfig_Call{Call: _e.mock.On("GetUserQuotaConfig", userID)}
}

func (_c *MockUsageManager_GetUserQuotaConfig_Call) Run(run func(userID uint)) *MockUsageManager_GetUserQuotaConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsageManager_GetUserQuotaConfig_Call) Return(userQuotaConfig *models.UserQuotaConfig, err error) *MockUsageManager_GetUserQuotaConfig_Call {
	_c.Call.Return(userQuotaConfig, err)
	return _c
}

func (_c *MockUsageManager_GetUserQuotaConfig_Call) RunAndReturn(run func(userID uint) (*models.UserQuotaConfig, error)) *MockUsageManager_GetUserQuotaConfig_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDownload provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordDownload(userID uint, uploadID uint, bytes uint64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, uint64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDownload'
type MockUsageManager_RecordDownload_Call struct {
	*mock.Call
}

// RecordDownload is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes uint64
//   - ip string
func (_e *MockUsageManager_Expecter) RecordDownload(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockUsageManager_RecordDownload_Call {
	return &MockUsageManager_RecordDownload_Call{Call: _e.mock.On("RecordDownload", userID, uploadID, bytes, ip)}
}

func (_c *MockUsageManager_RecordDownload_Call) Run(run func(userID uint, uploadID uint, bytes uint64, ip string)) *MockUsageManager_RecordDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordDownload_Call) Return(err error) *MockUsageManager_RecordDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordDownload_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes uint64, ip string) error) *MockUsageManager_RecordDownload_Call {
	_c.Call.Return(run)
	return _c
}

// RecordStorageChange provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordStorageChange(userID uint, uploadID uint, bytes int64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordStorageChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, int64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordStorageChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStorageChange'
type MockUsageManager_RecordStorageChange_Call struct {
	*mock.Call
}

// RecordStorageChange is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes int64
//   - ip string
func (_e *MockUsageManager_Expecter) RecordStorageChange(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockUsageManager_RecordStorageChange_Call {
	return &MockUsageManager_RecordStorageChange_Call{Call: _e.mock.On("RecordStorageChange", userID, uploadID, bytes, ip)}
}

func (_c *MockUsageManager_RecordStorageChange_Call) Run(run func(userID uint, uploadID uint, bytes int64, ip string)) *MockUsageManager_RecordStorageChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordStorageChange_Call) Return(err error) *MockUsageManager_RecordStorageChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordStorageChange_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes int64, ip string) error) *MockUsageManager_RecordStorageChange_Call {
	_c.Call.Return(run)
	return _c
}

// RecordUpload provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordUpload(userID uint, uploadID uint, bytes uint64, ip string) error {
	ret := _mock.Called(userID, uploadID, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for RecordUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, uint64, string) error); ok {
		r0 = returnFunc(userID, uploadID, bytes, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUpload'
type MockUsageManager_RecordUpload_Call struct {
	*mock.Call
}

// RecordUpload is a helper method to define mock.On call
//   - userID uint
//   - uploadID uint
//   - bytes uint64
//   - ip string
func (_e *MockUsageManager_Expecter) RecordUpload(userID interface{}, uploadID interface{}, bytes interface{}, ip interface{}) *MockUsageManager_RecordUpload_Call {
	return &MockUsageManager_RecordUpload_Call{Call: _e.mock.On("RecordUpload", userID, uploadID, bytes, ip)}
}

func (_c *MockUsageManager_RecordUpload_Call) Run(run func(userID uint, uploadID uint, bytes uint64, ip string)) *MockUsageManager_RecordUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordUpload_Call) Return(err error) *MockUsageManager_RecordUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordUpload_Call) RunAndReturn(run func(userID uint, uploadID uint, bytes uint64, ip string) error) *MockUsageManager_RecordUpload_Call {
	_c.Call.Return(run)
	return _c
}

// RecordUserUsageDetail provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) RecordUserUsageDetail(detail *UserUsageDetail) error {
	ret := _mock.Called(detail)

	if len(ret) == 0 {
		panic("no return value specified for RecordUserUsageDetail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*UserUsageDetail) error); ok {
		r0 = returnFunc(detail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_RecordUserUsageDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUserUsageDetail'
type MockUsageManager_RecordUserUsageDetail_Call struct {
	*mock.Call
}

// RecordUserUsageDetail is a helper method to define mock.On call
//   - detail *UserUsageDetail
func (_e *MockUsageManager_Expecter) RecordUserUsageDetail(detail interface{}) *MockUsageManager_RecordUserUsageDetail_Call {
	return &MockUsageManager_RecordUserUsageDetail_Call{Call: _e.mock.On("RecordUserUsageDetail", detail)}
}

func (_c *MockUsageManager_RecordUserUsageDetail_Call) Run(run func(detail *UserUsageDetail)) *MockUsageManager_RecordUserUsageDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *UserUsageDetail
		if args[0] != nil {
			arg0 = args[0].(*UserUsageDetail)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsageManager_RecordUserUsageDetail_Call) Return(err error) *MockUsageManager_RecordUserUsageDetail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_RecordUserUsageDetail_Call) RunAndReturn(run func(detail *UserUsageDetail) error) *MockUsageManager_RecordUserUsageDetail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDailyUsage provides a mock function for the type MockUsageManager
func (_mock *MockUsageManager) UpdateDailyUsage(userID uint, usageType UsageType, bytes int64) error {
	ret := _mock.Called(userID, usageType, bytes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDailyUsage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, UsageType, int64) error); ok {
		r0 = returnFunc(userID, usageType, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsageManager_UpdateDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDailyUsage'
type MockUsageManager_UpdateDailyUsage_Call struct {
	*mock.Call
}

// UpdateDailyUsage is a helper method to define mock.On call
//   - userID uint
//   - usageType UsageType
//   - bytes int64
func (_e *MockUsageManager_Expecter) UpdateDailyUsage(userID interface{}, usageType interface{}, bytes interface{}) *MockUsageManager_UpdateDailyUsage_Call {
	return &MockUsageManager_UpdateDailyUsage_Call{Call: _e.mock.On("UpdateDailyUsage", userID, usageType, bytes)}
}

func (_c *MockUsageManager_UpdateDailyUsage_Call) Run(run func(userID uint, usageType UsageType, bytes int64)) *MockUsageManager_UpdateDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 UsageType
		if args[1] != nil {
			arg1 = args[1].(UsageType)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsageManager_UpdateDailyUsage_Call) Return(err error) *MockUsageManager_UpdateDailyUsage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsageManager_UpdateDailyUsage_Call) RunAndReturn(run func(userID uint, usageType UsageType, bytes int64) error) *MockUsageManager_UpdateDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}
