// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-quota/internal/db/models"
)

// NewMockConfigManager creates a new instance of MockConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigManager {
	mock := &MockConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigManager is an autogenerated mock type for the ConfigManager type
type MockConfigManager struct {
	mock.Mock
}

type MockConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigManager) EXPECT() *MockConfigManager_Expecter {
	return &MockConfigManager_Expecter{mock: &_m.Mock}
}

// GetPolicyEnforcer provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetPolicyEnforcer(ctx context.Context, userID uint) (PolicyEnforcer, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyEnforcer")
	}

	var r0 PolicyEnforcer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (PolicyEnforcer, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) PolicyEnforcer); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PolicyEnforcer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_GetPolicyEnforcer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicyEnforcer'
type MockConfigManager_GetPolicyEnforcer_Call struct {
	*mock.Call
}

// GetPolicyEnforcer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockConfigManager_Expecter) GetPolicyEnforcer(ctx interface{}, userID interface{}) *MockConfigManager_GetPolicyEnforcer_Call {
	return &MockConfigManager_GetPolicyEnforcer_Call{Call: _e.mock.On("GetPolicyEnforcer", ctx, userID)}
}

func (_c *MockConfigManager_GetPolicyEnforcer_Call) Run(run func(ctx context.Context, userID uint)) *MockConfigManager_GetPolicyEnforcer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigManager_GetPolicyEnforcer_Call) Return(policyEnforcer PolicyEnforcer, err error) *MockConfigManager_GetPolicyEnforcer_Call {
	_c.Call.Return(policyEnforcer, err)
	return _c
}

func (_c *MockConfigManager_GetPolicyEnforcer_Call) RunAndReturn(run func(ctx context.Context, userID uint) (PolicyEnforcer, error)) *MockConfigManager_GetPolicyEnforcer_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAllowanceGrants provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetUserAllowanceGrants(ctx context.Context, userID uint) ([]*models.AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAllowanceGrants")
	}

	var r0 []*models.AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_GetUserAllowanceGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAllowanceGrants'
type MockConfigManager_GetUserAllowanceGrants_Call struct {
	*mock.Call
}

// GetUserAllowanceGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockConfigManager_Expecter) GetUserAllowanceGrants(ctx interface{}, userID interface{}) *MockConfigManager_GetUserAllowanceGrants_Call {
	return &MockConfigManager_GetUserAllowanceGrants_Call{Call: _e.mock.On("GetUserAllowanceGrants", ctx, userID)}
}

func (_c *MockConfigManager_GetUserAllowanceGrants_Call) Run(run func(ctx context.Context, userID uint)) *MockConfigManager_GetUserAllowanceGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigManager_GetUserAllowanceGrants_Call) Return(allowanceGrants []*models.AllowanceGrant, err error) *MockConfigManager_GetUserAllowanceGrants_Call {
	_c.Call.Return(allowanceGrants, err)
	return _c
}

func (_c *MockConfigManager_GetUserAllowanceGrants_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]*models.AllowanceGrant, error)) *MockConfigManager_GetUserAllowanceGrants_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAllowanceGrantsByType provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetUserAllowanceGrantsByType(ctx context.Context, userID uint, grantType models.GrantType) ([]*models.AllowanceGrant, error) {
	ret := _mock.Called(ctx, userID, grantType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAllowanceGrantsByType")
	}

	var r0 []*models.AllowanceGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, models.GrantType) ([]*models.AllowanceGrant, error)); ok {
		return returnFunc(ctx, userID, grantType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, models.GrantType) []*models.AllowanceGrant); ok {
		r0 = returnFunc(ctx, userID, grantType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AllowanceGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, models.GrantType) error); ok {
		r1 = returnFunc(ctx, userID, grantType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_GetUserAllowanceGrantsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAllowanceGrantsByType'
type MockConfigManager_GetUserAllowanceGrantsByType_Call struct {
	*mock.Call
}

// GetUserAllowanceGrantsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - grantType models.GrantType
func (_e *MockConfigManager_Expecter) GetUserAllowanceGrantsByType(ctx interface{}, userID interface{}, grantType interface{}) *MockConfigManager_GetUserAllowanceGrantsByType_Call {
	return &MockConfigManager_GetUserAllowanceGrantsByType_Call{Call: _e.mock.On("GetUserAllowanceGrantsByType", ctx, userID, grantType)}
}

func (_c *MockConfigManager_GetUserAllowanceGrantsByType_Call) Run(run func(ctx context.Context, userID uint, grantType models.GrantType)) *MockConfigManager_GetUserAllowanceGrantsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 models.GrantType
		if args[2] != nil {
			arg2 = args[2].(models.GrantType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigManager_GetUserAllowanceGrantsByType_Call) Return(allowanceGrants []*models.AllowanceGrant, err error) *MockConfigManager_GetUserAllowanceGrantsByType_Call {
	_c.Call.Return(allowanceGrants, err)
	return _c
}

func (_c *MockConfigManager_GetUserAllowanceGrantsByType_Call) RunAndReturn(run func(ctx context.Context, userID uint, grantType models.GrantType) ([]*models.AllowanceGrant, error)) *MockConfigManager_GetUserAllowanceGrantsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserQuotaConfig provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) GetUserQuotaConfig(ctx context.Context, userID uint) (*models.UserQuotaConfig, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserQuotaConfig")
	}

	var r0 *models.UserQuotaConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.UserQuotaConfig, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.UserQuotaConfig); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserQuotaConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_GetUserQuotaConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserQuotaConfig'
type MockConfigManager_GetUserQuotaConfig_Call struct {
	*mock.Call
}

// GetUserQuotaConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockConfigManager_Expecter) GetUserQuotaConfig(ctx interface{}, userID interface{}) *MockConfigManager_GetUserQuotaConfig_Call {
	return &MockConfigManager_GetUserQuotaConfig_Call{Call: _e.mock.On("GetUserQuotaConfig", ctx, userID)}
}

func (_c *MockConfigManager_GetUserQuotaConfig_Call) Run(run func(ctx context.Context, userID uint)) *MockConfigManager_GetUserQuotaConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigManager_GetUserQuotaConfig_Call) Return(userQuotaConfig *models.UserQuotaConfig, err error) *MockConfigManager_GetUserQuotaConfig_Call {
	_c.Call.Return(userQuotaConfig, err)
	return _c
}

func (_c *MockConfigManager_GetUserQuotaConfig_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*models.UserQuotaConfig, error)) *MockConfigManager_GetUserQuotaConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveEffectiveLimits provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) ResolveEffectiveLimits(ctx context.Context, userID uint) (*EffectiveLimits, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveEffectiveLimits")
	}

	var r0 *EffectiveLimits
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*EffectiveLimits, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *EffectiveLimits); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EffectiveLimits)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_ResolveEffectiveLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveEffectiveLimits'
type MockConfigManager_ResolveEffectiveLimits_Call struct {
	*mock.Call
}

// ResolveEffectiveLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockConfigManager_Expecter) ResolveEffectiveLimits(ctx interface{}, userID interface{}) *MockConfigManager_ResolveEffectiveLimits_Call {
	return &MockConfigManager_ResolveEffectiveLimits_Call{Call: _e.mock.On("ResolveEffectiveLimits", ctx, userID)}
}

func (_c *MockConfigManager_ResolveEffectiveLimits_Call) Run(run func(ctx context.Context, userID uint)) *MockConfigManager_ResolveEffectiveLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigManager_ResolveEffectiveLimits_Call) Return(effectiveLimits *EffectiveLimits, err error) *MockConfigManager_ResolveEffectiveLimits_Call {
	_c.Call.Return(effectiveLimits, err)
	return _c
}

func (_c *MockConfigManager_ResolveEffectiveLimits_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*EffectiveLimits, error)) *MockConfigManager_ResolveEffectiveLimits_Call {
	_c.Call.Return(run)
	return _c
}
