// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-quota/internal/db/models"
)

// NewMockReservationManager creates a new instance of MockReservationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationManager {
	mock := &MockReservationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReservationManager is an autogenerated mock type for the ReservationManager type
type MockReservationManager struct {
	mock.Mock
}

type MockReservationManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationManager) EXPECT() *MockReservationManager_Expecter {
	return &MockReservationManager_Expecter{mock: &_m.Mock}
}

// CleanupStaleReservations provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) CleanupStaleReservations(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupStaleReservations")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_CleanupStaleReservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupStaleReservations'
type MockReservationManager_CleanupStaleReservations_Call struct {
	*mock.Call
}

// CleanupStaleReservations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationManager_Expecter) CleanupStaleReservations(ctx interface{}) *MockReservationManager_CleanupStaleReservations_Call {
	return &MockReservationManager_CleanupStaleReservations_Call{Call: _e.mock.On("CleanupStaleReservations", ctx)}
}

func (_c *MockReservationManager_CleanupStaleReservations_Call) Run(run func(ctx context.Context)) *MockReservationManager_CleanupStaleReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationManager_CleanupStaleReservations_Call) Return(n int64, err error) *MockReservationManager_CleanupStaleReservations_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReservationManager_CleanupStaleReservations_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockReservationManager_CleanupStaleReservations_Call {
	_c.Call.Return(run)
	return _c
}

// CleanupStaleReservationsForUser provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) CleanupStaleReservationsForUser(ctx context.Context, userID uint) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CleanupStaleReservationsForUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_CleanupStaleReservationsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupStaleReservationsForUser'
type MockReservationManager_CleanupStaleReservationsForUser_Call struct {
	*mock.Call
}

// CleanupStaleReservationsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockReservationManager_Expecter) CleanupStaleReservationsForUser(ctx interface{}, userID interface{}) *MockReservationManager_CleanupStaleReservationsForUser_Call {
	return &MockReservationManager_CleanupStaleReservationsForUser_Call{Call: _e.mock.On("CleanupStaleReservationsForUser", ctx, userID)}
}

func (_c *MockReservationManager_CleanupStaleReservationsForUser_Call) Run(run func(ctx context.Context, userID uint)) *MockReservationManager_CleanupStaleReservationsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationManager_CleanupStaleReservationsForUser_Call) Return(n int64, err error) *MockReservationManager_CleanupStaleReservationsForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReservationManager_CleanupStaleReservationsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) (int64, error)) *MockReservationManager_CleanupStaleReservationsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// CommitReservation provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) CommitReservation(ctx context.Context, reservationID uint, uploadID uint) error {
	ret := _mock.Called(ctx, reservationID, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for CommitReservation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, reservationID, uploadID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationManager_CommitReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitReservation'
type MockReservationManager_CommitReservation_Call struct {
	*mock.Call
}

// CommitReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID uint
//   - uploadID uint
func (_e *MockReservationManager_Expecter) CommitReservation(ctx interface{}, reservationID interface{}, uploadID interface{}) *MockReservationManager_CommitReservation_Call {
	return &MockReservationManager_CommitReservation_Call{Call: _e.mock.On("CommitReservation", ctx, reservationID, uploadID)}
}

func (_c *MockReservationManager_CommitReservation_Call) Run(run func(ctx context.Context, reservationID uint, uploadID uint)) *MockReservationManager_CommitReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationManager_CommitReservation_Call) Return(err error) *MockReservationManager_CommitReservation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationManager_CommitReservation_Call) RunAndReturn(run func(ctx context.Context, reservationID uint, uploadID uint) error) *MockReservationManager_CommitReservation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReservation provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) CreateReservation(ctx context.Context, userID uint, usageType UsageType, bytes uint64, ip string) (*models.QuotaReservation, error) {
	ret := _mock.Called(ctx, userID, usageType, bytes, ip)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 *models.QuotaReservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType, uint64, string) (*models.QuotaReservation, error)); ok {
		return returnFunc(ctx, userID, usageType, bytes, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType, uint64, string) *models.QuotaReservation); ok {
		r0 = returnFunc(ctx, userID, usageType, bytes, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaReservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, UsageType, uint64, string) error); ok {
		r1 = returnFunc(ctx, userID, usageType, bytes, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_CreateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReservation'
type MockReservationManager_CreateReservation_Call struct {
	*mock.Call
}

// CreateReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - usageType UsageType
//   - bytes uint64
//   - ip string
func (_e *MockReservationManager_Expecter) CreateReservation(ctx interface{}, userID interface{}, usageType interface{}, bytes interface{}, ip interface{}) *MockReservationManager_CreateReservation_Call {
	return &MockReservationManager_CreateReservation_Call{Call: _e.mock.On("CreateReservation", ctx, userID, usageType, bytes, ip)}
}

func (_c *MockReservationManager_CreateReservation_Call) Run(run func(ctx context.Context, userID uint, usageType UsageType, bytes uint64, ip string)) *MockReservationManager_CreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReservationManager_CreateReservation_Call) Return(quotaReservation *models.QuotaReservation, err error) *MockReservationManager_CreateReservation_Call {
	_c.Call.Return(quotaReservation, err)
	return _c
}

func (_c *MockReservationManager_CreateReservation_Call) RunAndReturn(run func(ctx context.Context, userID uint, usageType UsageType, bytes uint64, ip string) (*models.QuotaReservation, error)) *MockReservationManager_CreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingReservationsForUser provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) GetPendingReservationsForUser(ctx context.Context, userID uint) ([]*models.QuotaReservation, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingReservationsForUser")
	}

	var r0 []*models.QuotaReservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]*models.QuotaReservation, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []*models.QuotaReservation); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.QuotaReservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_GetPendingReservationsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingReservationsForUser'
type MockReservationManager_GetPendingReservationsForUser_Call struct {
	*mock.Call
}

// GetPendingReservationsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockReservationManager_Expecter) GetPendingReservationsForUser(ctx interface{}, userID interface{}) *MockReservationManager_GetPendingReservationsForUser_Call {
	return &MockReservationManager_GetPendingReservationsForUser_Call{Call: _e.mock.On("GetPendingReservationsForUser", ctx, userID)}
}

func (_c *MockReservationManager_GetPendingReservationsForUser_Call) Run(run func(ctx context.Context, userID uint)) *MockReservationManager_GetPendingReservationsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationManager_GetPendingReservationsForUser_Call) Return(quotaReservations []*models.QuotaReservation, err error) *MockReservationManager_GetPendingReservationsForUser_Call {
	_c.Call.Return(quotaReservations, err)
	return _c
}

func (_c *MockReservationManager_GetPendingReservationsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]*models.QuotaReservation, error)) *MockReservationManager_GetPendingReservationsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetReservationByID provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) GetReservationByID(ctx context.Context, reservationID uint) (*models.QuotaReservation, error) {
	ret := _mock.Called(ctx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationByID")
	}

	var r0 *models.QuotaReservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.QuotaReservation, error)); ok {
		return returnFunc(ctx, reservationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.QuotaReservation); ok {
		r0 = returnFunc(ctx, reservationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaReservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, reservationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_GetReservationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReservationByID'
type MockReservationManager_GetReservationByID_Call struct {
	*mock.Call
}

// GetReservationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID uint
func (_e *MockReservationManager_Expecter) GetReservationByID(ctx interface{}, reservationID interface{}) *MockReservationManager_GetReservationByID_Call {
	return &MockReservationManager_GetReservationByID_Call{Call: _e.mock.On("GetReservationByID", ctx, reservationID)}
}

func (_c *MockReservationManager_GetReservationByID_Call) Run(run func(ctx context.Context, reservationID uint)) *MockReservationManager_GetReservationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationManager_GetReservationByID_Call) Return(quotaReservation *models.QuotaReservation, err error) *MockReservationManager_GetReservationByID_Call {
	_c.Call.Return(quotaReservation, err)
	return _c
}

func (_c *MockReservationManager_GetReservationByID_Call) RunAndReturn(run func(ctx context.Context, reservationID uint) (*models.QuotaReservation, error)) *MockReservationManager_GetReservationByID_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseReservation provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) ReleaseReservation(ctx context.Context, reservationID uint) error {
	ret := _mock.Called(ctx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseReservation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, reservationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationManager_ReleaseReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseReservation'
type MockReservationManager_ReleaseReservation_Call struct {
	*mock.Call
}

// ReleaseReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID uint
func (_e *MockReservationManager_Expecter) ReleaseReservation(ctx interface{}, reservationID interface{}) *MockReservationManager_ReleaseReservation_Call {
	return &MockReservationManager_ReleaseReservation_Call{Call: _e.mock.On("ReleaseReservation", ctx, reservationID)}
}

func (_c *MockReservationManager_ReleaseReservation_Call) Run(run func(ctx context.Context, reservationID uint)) *MockReservationManager_ReleaseReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationManager_ReleaseReservation_Call) Return(err error) *MockReservationManager_ReleaseReservation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationManager_ReleaseReservation_Call) RunAndReturn(run func(ctx context.Context, reservationID uint) error) *MockReservationManager_ReleaseReservation_Call {
	_c.Call.Return(run)
	return _c
}

// SumPendingBytesForUser provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) SumPendingBytesForUser(ctx context.Context, userID uint, usageType UsageType) (uint64, error) {
	ret := _mock.Called(ctx, userID, usageType)

	if len(ret) == 0 {
		panic("no return value specified for SumPendingBytesForUser")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType) (uint64, error)); ok {
		return returnFunc(ctx, userID, usageType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType) uint64); ok {
		r0 = returnFunc(ctx, userID, usageType)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, UsageType) error); ok {
		r1 = returnFunc(ctx, userID, usageType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_SumPendingBytesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumPendingBytesForUser'
type MockReservationManager_SumPendingBytesForUser_Call struct {
	*mock.Call
}

// SumPendingBytesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - usageType UsageType
func (_e *MockReservationManager_Expecter) SumPendingBytesForUser(ctx interface{}, userID interface{}, usageType interface{}) *MockReservationManager_SumPendingBytesForUser_Call {
	return &MockReservationManager_SumPendingBytesForUser_Call{Call: _e.mock.On("SumPendingBytesForUser", ctx, userID, usageType)}
}

func (_c *MockReservationManager_SumPendingBytesForUser_Call) Run(run func(ctx context.Context, userID uint, usageType UsageType)) *MockReservationManager_SumPendingBytesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationManager_SumPendingBytesForUser_Call) Return(v uint64, err error) *MockReservationManager_SumPendingBytesForUser_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockReservationManager_SumPendingBytesForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, usageType UsageType) (uint64, error)) *MockReservationManager_SumPendingBytesForUser_Call {
	_c.Call.Return(run)
	return _c
}
