// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReservationManager creates a new instance of MockReservationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationManager {
	mock := &MockReservationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReservationManager is an autogenerated mock type for the ReservationManager type
type MockReservationManager struct {
	mock.Mock
}

type MockReservationManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationManager) EXPECT() *MockReservationManager_Expecter {
	return &MockReservationManager_Expecter{mock: &_m.Mock}
}

// CountPendingReservationsForUser provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) CountPendingReservationsForUser(ctx context.Context, userID uint, usageType UsageType) int {
	ret := _mock.Called(ctx, userID, usageType)

	if len(ret) == 0 {
		panic("no return value specified for CountPendingReservationsForUser")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType) int); ok {
		r0 = returnFunc(ctx, userID, usageType)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockReservationManager_CountPendingReservationsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPendingReservationsForUser'
type MockReservationManager_CountPendingReservationsForUser_Call struct {
	*mock.Call
}

// CountPendingReservationsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - usageType UsageType
func (_e *MockReservationManager_Expecter) CountPendingReservationsForUser(ctx interface{}, userID interface{}, usageType interface{}) *MockReservationManager_CountPendingReservationsForUser_Call {
	return &MockReservationManager_CountPendingReservationsForUser_Call{Call: _e.mock.On("CountPendingReservationsForUser", ctx, userID, usageType)}
}

func (_c *MockReservationManager_CountPendingReservationsForUser_Call) Run(run func(ctx context.Context, userID uint, usageType UsageType)) *MockReservationManager_CountPendingReservationsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationManager_CountPendingReservationsForUser_Call) Return(n int) *MockReservationManager_CountPendingReservationsForUser_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockReservationManager_CountPendingReservationsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, usageType UsageType) int) *MockReservationManager_CountPendingReservationsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetReservation provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) GetReservation(uuid string) Reservation {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetReservation")
	}

	var r0 Reservation
	if returnFunc, ok := ret.Get(0).(func(string) Reservation); ok {
		r0 = returnFunc(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Reservation)
		}
	}
	return r0
}

// MockReservationManager_GetReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReservation'
type MockReservationManager_GetReservation_Call struct {
	*mock.Call
}

// GetReservation is a helper method to define mock.On call
//   - uuid string
func (_e *MockReservationManager_Expecter) GetReservation(uuid interface{}) *MockReservationManager_GetReservation_Call {
	return &MockReservationManager_GetReservation_Call{Call: _e.mock.On("GetReservation", uuid)}
}

func (_c *MockReservationManager_GetReservation_Call) Run(run func(uuid string)) *MockReservationManager_GetReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationManager_GetReservation_Call) Return(reservation Reservation) *MockReservationManager_GetReservation_Call {
	_c.Call.Return(reservation)
	return _c
}

func (_c *MockReservationManager_GetReservation_Call) RunAndReturn(run func(uuid string) Reservation) *MockReservationManager_GetReservation_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) Reserve(ctx context.Context, userID uint, usageType UsageType, bytes int64) (Reservation, error) {
	ret := _mock.Called(ctx, userID, usageType, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType, int64) (Reservation, error)); ok {
		return returnFunc(ctx, userID, usageType, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType, int64) Reservation); ok {
		r0 = returnFunc(ctx, userID, usageType, bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, UsageType, int64) error); ok {
		r1 = returnFunc(ctx, userID, usageType, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationManager_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockReservationManager_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - usageType UsageType
//   - bytes int64
func (_e *MockReservationManager_Expecter) Reserve(ctx interface{}, userID interface{}, usageType interface{}, bytes interface{}) *MockReservationManager_Reserve_Call {
	return &MockReservationManager_Reserve_Call{Call: _e.mock.On("Reserve", ctx, userID, usageType, bytes)}
}

func (_c *MockReservationManager_Reserve_Call) Run(run func(ctx context.Context, userID uint, usageType UsageType, bytes int64)) *MockReservationManager_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationManager_Reserve_Call) Return(reservation Reservation, err error) *MockReservationManager_Reserve_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *MockReservationManager_Reserve_Call) RunAndReturn(run func(ctx context.Context, userID uint, usageType UsageType, bytes int64) (Reservation, error)) *MockReservationManager_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// SumPendingBytesForUser provides a mock function for the type MockReservationManager
func (_mock *MockReservationManager) SumPendingBytesForUser(ctx context.Context, userID uint, usageType UsageType) int64 {
	ret := _mock.Called(ctx, userID, usageType)

	if len(ret) == 0 {
		panic("no return value specified for SumPendingBytesForUser")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, UsageType) int64); ok {
		r0 = returnFunc(ctx, userID, usageType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockReservationManager_SumPendingBytesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumPendingBytesForUser'
type MockReservationManager_SumPendingBytesForUser_Call struct {
	*mock.Call
}

// SumPendingBytesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - usageType UsageType
func (_e *MockReservationManager_Expecter) SumPendingBytesForUser(ctx interface{}, userID interface{}, usageType interface{}) *MockReservationManager_SumPendingBytesForUser_Call {
	return &MockReservationManager_SumPendingBytesForUser_Call{Call: _e.mock.On("SumPendingBytesForUser", ctx, userID, usageType)}
}

func (_c *MockReservationManager_SumPendingBytesForUser_Call) Run(run func(ctx context.Context, userID uint, usageType UsageType)) *MockReservationManager_SumPendingBytesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 UsageType
		if args[2] != nil {
			arg2 = args[2].(UsageType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationManager_SumPendingBytesForUser_Call) Return(n int64) *MockReservationManager_SumPendingBytesForUser_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockReservationManager_SumPendingBytesForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, usageType UsageType) int64) *MockReservationManager_SumPendingBytesForUser_Call {
	_c.Call.Return(run)
	return _c
}
